//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 
namespace AxMyData.AADE {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0", IsNullable=false)]
    public partial class InvoicesDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoice")]
        public AadeBookInvoiceType[] invoice;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class AadeBookInvoiceType {
        
        /// <remarks/>
        public string uid;
        
        /// <remarks/>
        public long mark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool markSpecified;
        
        /// <remarks/>
        public long cancelledByMark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cancelledByMarkSpecified;
        
        /// <remarks/>
        public string authenticationCode;
        
        /// <remarks/>
        public sbyte transmissionFailure;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transmissionFailureSpecified;
        
        /// <remarks/>
        public PartyType issuer;
        
        /// <remarks/>
        public PartyType counterpart;
        
        /// <remarks/>
        public InvoiceHeaderType invoiceHeader;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("paymentMethodDetails", IsNullable=false)]
        public PaymentMethodDetailType[] paymentMethods;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoiceDetails")]
        public InvoiceRowType[] invoiceDetails;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("taxes", IsNullable=false)]
        public TaxTotalsType[] taxesTotals;
        
        /// <remarks/>
        public InvoiceSummaryType invoiceSummary;
        
        /// <remarks/>
        public string qrCodeUrl;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("otherTransportDetails")]
        public TransportDetailType[] otherTransportDetails;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class PartyType {
        
        /// <remarks/>
        public string vatNumber;
        
        /// <remarks/>
        public CountryType country;
        
        /// <remarks/>
        public int branch;
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public AddressType address;
        
        /// <remarks/>
        public string documentIdNo;
        
        /// <remarks/>
        public string supplyAccountNo;
        
        /// <remarks/>
        public CountryType countryDocumentId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countryDocumentIdSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum CountryType {
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AW,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        BJ,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        BW,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        CX,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        EH,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        GF,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GS,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        IQ,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JE,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        KH,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        KP,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LK,
        
        /// <remarks/>
        LR,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        ME,
        
        /// <remarks/>
        MF,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MM,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        OC,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        PH,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PY,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SJ,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TJ,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        UA,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        US,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VG,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        VN,
        
        /// <remarks/>
        VU,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        YE,
        
        /// <remarks/>
        YT,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        ZM,
        
        /// <remarks/>
        ZW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class AddressType {
        
        /// <remarks/>
        public string street;
        
        /// <remarks/>
        public string number;
        
        /// <remarks/>
        public string postalCode;
        
        /// <remarks/>
        public string city;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0")]
    public partial class PaymentMethodType {
        
        /// <remarks/>
        public long invoiceMark;
        
        /// <remarks/>
        public long paymentMethodMark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentMethodMarkSpecified;
        
        /// <remarks/>
        public string entityVatNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentMethodDetails")]
        public PaymentMethodDetailType[] paymentMethodDetails;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class PaymentMethodDetailType {
        
        /// <remarks/>
        public int type;
        
        /// <remarks/>
        public decimal amount;
        
        /// <remarks/>
        public string paymentMethodInfo;
        
        /// <remarks/>
        public decimal tipAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipAmountSpecified;
        
        /// <remarks/>
        public string transactionId;
        
        /// <remarks/>
        public ProviderSignatureType ProvidersSignature;
        
        /// <remarks/>
        public ECRTokenType ECRToken;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ProviderSignatureType {
        
        /// <remarks/>
        public string SigningAuthor;
        
        /// <remarks/>
        public string Signature;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ECRTokenType {
        
        /// <remarks/>
        public string SigningAuthor;
        
        /// <remarks/>
        public string SessionNumber;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class InvoicesExpensesClassificationDetailType {
        
        /// <remarks/>
        public int lineNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesClassificationDetailData")]
        public ExpensesClassificationType[] expensesClassificationDetailData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class ExpensesClassificationType {
        
        /// <remarks/>
        public ExpensesClassificationTypeClassificationType classificationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationTypeSpecified;
        
        /// <remarks/>
        public ExpensesClassificationCategoryType classificationCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationCategorySpecified;
        
        /// <remarks/>
        public decimal amount;
        
        /// <remarks/>
        public decimal vatAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatAmountSpecified;
        
        /// <remarks/>
        public int vatCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatCategorySpecified;
        
        /// <remarks/>
        public int vatExemptionCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatExemptionCategorySpecified;
        
        /// <remarks/>
        public sbyte id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum ExpensesClassificationTypeClassificationType {
        
        /// <remarks/>
        E3_101,
        
        /// <remarks/>
        E3_102_001,
        
        /// <remarks/>
        E3_102_002,
        
        /// <remarks/>
        E3_102_003,
        
        /// <remarks/>
        E3_102_004,
        
        /// <remarks/>
        E3_102_005,
        
        /// <remarks/>
        E3_102_006,
        
        /// <remarks/>
        E3_104,
        
        /// <remarks/>
        E3_201,
        
        /// <remarks/>
        E3_202_001,
        
        /// <remarks/>
        E3_202_002,
        
        /// <remarks/>
        E3_202_003,
        
        /// <remarks/>
        E3_202_004,
        
        /// <remarks/>
        E3_202_005,
        
        /// <remarks/>
        E3_204,
        
        /// <remarks/>
        E3_207,
        
        /// <remarks/>
        E3_209,
        
        /// <remarks/>
        E3_301,
        
        /// <remarks/>
        E3_302_001,
        
        /// <remarks/>
        E3_302_002,
        
        /// <remarks/>
        E3_302_003,
        
        /// <remarks/>
        E3_302_004,
        
        /// <remarks/>
        E3_302_005,
        
        /// <remarks/>
        E3_304,
        
        /// <remarks/>
        E3_307,
        
        /// <remarks/>
        E3_309,
        
        /// <remarks/>
        E3_312,
        
        /// <remarks/>
        E3_313_001,
        
        /// <remarks/>
        E3_313_002,
        
        /// <remarks/>
        E3_313_003,
        
        /// <remarks/>
        E3_313_004,
        
        /// <remarks/>
        E3_313_005,
        
        /// <remarks/>
        E3_315,
        
        /// <remarks/>
        E3_581_001,
        
        /// <remarks/>
        E3_581_002,
        
        /// <remarks/>
        E3_581_003,
        
        /// <remarks/>
        E3_582,
        
        /// <remarks/>
        E3_583,
        
        /// <remarks/>
        E3_584,
        
        /// <remarks/>
        E3_585_001,
        
        /// <remarks/>
        E3_585_002,
        
        /// <remarks/>
        E3_585_003,
        
        /// <remarks/>
        E3_585_004,
        
        /// <remarks/>
        E3_585_005,
        
        /// <remarks/>
        E3_585_006,
        
        /// <remarks/>
        E3_585_007,
        
        /// <remarks/>
        E3_585_008,
        
        /// <remarks/>
        E3_585_009,
        
        /// <remarks/>
        E3_585_010,
        
        /// <remarks/>
        E3_585_011,
        
        /// <remarks/>
        E3_585_012,
        
        /// <remarks/>
        E3_585_013,
        
        /// <remarks/>
        E3_585_014,
        
        /// <remarks/>
        E3_585_015,
        
        /// <remarks/>
        E3_585_016,
        
        /// <remarks/>
        E3_586,
        
        /// <remarks/>
        E3_587,
        
        /// <remarks/>
        E3_588,
        
        /// <remarks/>
        E3_589,
        
        /// <remarks/>
        E3_881_001,
        
        /// <remarks/>
        E3_881_002,
        
        /// <remarks/>
        E3_881_003,
        
        /// <remarks/>
        E3_881_004,
        
        /// <remarks/>
        E3_882_001,
        
        /// <remarks/>
        E3_882_002,
        
        /// <remarks/>
        E3_882_003,
        
        /// <remarks/>
        E3_882_004,
        
        /// <remarks/>
        E3_883_001,
        
        /// <remarks/>
        E3_883_002,
        
        /// <remarks/>
        E3_883_003,
        
        /// <remarks/>
        E3_883_004,
        
        /// <remarks/>
        VAT_361,
        
        /// <remarks/>
        VAT_362,
        
        /// <remarks/>
        VAT_363,
        
        /// <remarks/>
        VAT_364,
        
        /// <remarks/>
        VAT_365,
        
        /// <remarks/>
        VAT_366,
        
        /// <remarks/>
        E3_103,
        
        /// <remarks/>
        E3_203,
        
        /// <remarks/>
        E3_303,
        
        /// <remarks/>
        E3_208,
        
        /// <remarks/>
        E3_308,
        
        /// <remarks/>
        E3_314,
        
        /// <remarks/>
        E3_106,
        
        /// <remarks/>
        E3_205,
        
        /// <remarks/>
        E3_305,
        
        /// <remarks/>
        E3_210,
        
        /// <remarks/>
        E3_310,
        
        /// <remarks/>
        E3_318,
        
        /// <remarks/>
        E3_598_002,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public enum ExpensesClassificationCategoryType {
        
        /// <remarks/>
        category2_1,
        
        /// <remarks/>
        category2_2,
        
        /// <remarks/>
        category2_3,
        
        /// <remarks/>
        category2_4,
        
        /// <remarks/>
        category2_5,
        
        /// <remarks/>
        category2_6,
        
        /// <remarks/>
        category2_7,
        
        /// <remarks/>
        category2_8,
        
        /// <remarks/>
        category2_9,
        
        /// <remarks/>
        category2_10,
        
        /// <remarks/>
        category2_11,
        
        /// <remarks/>
        category2_12,
        
        /// <remarks/>
        category2_13,
        
        /// <remarks/>
        category2_14,
        
        /// <remarks/>
        category2_95,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class InvoiceExpensesClassificationType {
        
        /// <remarks/>
        public long invoiceMark;
        
        /// <remarks/>
        public long classificationMark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationMarkSpecified;
        
        /// <remarks/>
        public string entityVatNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoicesExpensesClassificationDetails", typeof(InvoicesExpensesClassificationDetailType))]
        [System.Xml.Serialization.XmlElementAttribute("transactionMode", typeof(int))]
        public object[] Items;
        
        /// <remarks/>
        public sbyte classificationPostMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationPostModeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class InvoicesIncomeClassificationDetailType {
        
        /// <remarks/>
        public int lineNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeClassificationDetailData")]
        public IncomeClassificationType[] incomeClassificationDetailData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class IncomeClassificationType {
        
        /// <remarks/>
        public IncomeClassificationValueType classificationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationTypeSpecified;
        
        /// <remarks/>
        public IncomeClassificationCategoryType classificationCategory;
        
        /// <remarks/>
        public decimal amount;
        
        /// <remarks/>
        public sbyte id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public enum IncomeClassificationValueType {
        
        /// <remarks/>
        E3_106,
        
        /// <remarks/>
        E3_205,
        
        /// <remarks/>
        E3_210,
        
        /// <remarks/>
        E3_305,
        
        /// <remarks/>
        E3_310,
        
        /// <remarks/>
        E3_318,
        
        /// <remarks/>
        E3_561_001,
        
        /// <remarks/>
        E3_561_002,
        
        /// <remarks/>
        E3_561_003,
        
        /// <remarks/>
        E3_561_004,
        
        /// <remarks/>
        E3_561_005,
        
        /// <remarks/>
        E3_561_006,
        
        /// <remarks/>
        E3_561_007,
        
        /// <remarks/>
        E3_562,
        
        /// <remarks/>
        E3_563,
        
        /// <remarks/>
        E3_564,
        
        /// <remarks/>
        E3_565,
        
        /// <remarks/>
        E3_566,
        
        /// <remarks/>
        E3_567,
        
        /// <remarks/>
        E3_568,
        
        /// <remarks/>
        E3_570,
        
        /// <remarks/>
        E3_595,
        
        /// <remarks/>
        E3_596,
        
        /// <remarks/>
        E3_597,
        
        /// <remarks/>
        E3_880_001,
        
        /// <remarks/>
        E3_880_002,
        
        /// <remarks/>
        E3_880_003,
        
        /// <remarks/>
        E3_880_004,
        
        /// <remarks/>
        E3_881_001,
        
        /// <remarks/>
        E3_881_002,
        
        /// <remarks/>
        E3_881_003,
        
        /// <remarks/>
        E3_881_004,
        
        /// <remarks/>
        E3_598_001,
        
        /// <remarks/>
        E3_598_003,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public enum IncomeClassificationCategoryType {
        
        /// <remarks/>
        category1_1,
        
        /// <remarks/>
        category1_2,
        
        /// <remarks/>
        category1_3,
        
        /// <remarks/>
        category1_4,
        
        /// <remarks/>
        category1_5,
        
        /// <remarks/>
        category1_6,
        
        /// <remarks/>
        category1_7,
        
        /// <remarks/>
        category1_8,
        
        /// <remarks/>
        category1_9,
        
        /// <remarks/>
        category1_10,
        
        /// <remarks/>
        category1_95,
        
        /// <remarks/>
        category3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class InvoiceIncomeClassificationType {
        
        /// <remarks/>
        public long invoiceMark;
        
        /// <remarks/>
        public long classificationMark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationMarkSpecified;
        
        /// <remarks/>
        public string entityVatNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoicesIncomeClassificationDetails", typeof(InvoicesIncomeClassificationDetailType))]
        [System.Xml.Serialization.XmlElementAttribute("transactionMode", typeof(int))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class CancelledInvoiceType {
        
        /// <remarks/>
        public long invoiceMark;
        
        /// <remarks/>
        public long cancellationMark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime cancellationDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class continuationTokenType {
        
        /// <remarks/>
        public string nextPartitionKey;
        
        /// <remarks/>
        public string nextRowKey;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class TransportDetailType {
        
        /// <remarks/>
        public string vehicleNumber;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceSummaryType {
        
        /// <remarks/>
        public decimal totalNetValue;
        
        /// <remarks/>
        public decimal totalVatAmount;
        
        /// <remarks/>
        public decimal totalWithheldAmount;
        
        /// <remarks/>
        public decimal totalFeesAmount;
        
        /// <remarks/>
        public decimal totalStampDutyAmount;
        
        /// <remarks/>
        public decimal totalOtherTaxesAmount;
        
        /// <remarks/>
        public decimal totalDeductionsAmount;
        
        /// <remarks/>
        public decimal totalGrossValue;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeClassification")]
        public IncomeClassificationType[] incomeClassification;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesClassification")]
        public ExpensesClassificationType[] expensesClassification;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class TaxTotalsType {
        
        /// <remarks/>
        public sbyte taxType;
        
        /// <remarks/>
        public int taxCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxCategorySpecified;
        
        /// <remarks/>
        public decimal underlyingValue;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool underlyingValueSpecified;
        
        /// <remarks/>
        public decimal taxAmount;
        
        /// <remarks/>
        public sbyte id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ShipType {
        
        /// <remarks/>
        public string applicationId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime applicationDate;
        
        /// <remarks/>
        public string doy;
        
        /// <remarks/>
        public string shipId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceRowType {
        
        /// <remarks/>
        public int lineNumber;
        
        /// <remarks/>
        public int recType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recTypeSpecified;
        
        /// <remarks/>
        public string TaricNo;
        
        /// <remarks/>
        public string itemCode;
        
        /// <remarks/>
        public string itemDescr;
        
        /// <remarks/>
        public FuelCodes fuelCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuelCodeSpecified;
        
        /// <remarks/>
        public decimal quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified;
        
        /// <remarks/>
        public int measurementUnit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool measurementUnitSpecified;
        
        /// <remarks/>
        public int invoiceDetailType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invoiceDetailTypeSpecified;
        
        /// <remarks/>
        public decimal netValue;
        
        /// <remarks/>
        public int vatCategory;
        
        /// <remarks/>
        public decimal vatAmount;
        
        /// <remarks/>
        public int vatExemptionCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatExemptionCategorySpecified;
        
        /// <remarks/>
        public ShipType dienergia;
        
        /// <remarks/>
        public bool discountOption;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountOptionSpecified;
        
        /// <remarks/>
        public decimal withheldAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withheldAmountSpecified;
        
        /// <remarks/>
        public int withheldPercentCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withheldPercentCategorySpecified;
        
        /// <remarks/>
        public decimal stampDutyAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stampDutyAmountSpecified;
        
        /// <remarks/>
        public int stampDutyPercentCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stampDutyPercentCategorySpecified;
        
        /// <remarks/>
        public decimal feesAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feesAmountSpecified;
        
        /// <remarks/>
        public int feesPercentCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feesPercentCategorySpecified;
        
        /// <remarks/>
        public int otherTaxesPercentCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otherTaxesPercentCategorySpecified;
        
        /// <remarks/>
        public decimal otherTaxesAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otherTaxesAmountSpecified;
        
        /// <remarks/>
        public decimal deductionsAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deductionsAmountSpecified;
        
        /// <remarks/>
        public string lineComments;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeClassification")]
        public IncomeClassificationType[] incomeClassification;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesClassification")]
        public ExpensesClassificationType[] expensesClassification;
        
        /// <remarks/>
        public decimal quantity15;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantity15Specified;
        
        /// <remarks/>
        public int otherMeasurementUnitQuantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otherMeasurementUnitQuantitySpecified;
        
        /// <remarks/>
        public string otherMeasurementUnitTitle;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum FuelCodes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("72")]
        Item72,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("999")]
        Item999,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class OtherDeliveryNoteHeaderType {
        
        /// <remarks/>
        public AddressType loadingAddress;
        
        /// <remarks/>
        public AddressType deliveryAddress;
        
        /// <remarks/>
        public int startShippingBranch;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startShippingBranchSpecified;
        
        /// <remarks/>
        public int completeShippingBranch;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completeShippingBranchSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class EntityType {
        
        /// <remarks/>
        public int type;
        
        /// <remarks/>
        public PartyType entityData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceHeaderType {
        
        /// <remarks/>
        public string series;
        
        /// <remarks/>
        public string aa;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime issueDate;
        
        /// <remarks/>
        public InvoiceType invoiceType;
        
        /// <remarks/>
        public bool vatPaymentSuspension;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatPaymentSuspensionSpecified;
        
        /// <remarks/>
        public CurrencyType currency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencySpecified;
        
        /// <remarks/>
        public decimal exchangeRate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exchangeRateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("correlatedInvoices")]
        public long[] correlatedInvoices;
        
        /// <remarks/>
        public bool selfPricing;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selfPricingSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dispatchDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dispatchDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime dispatchTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dispatchTimeSpecified;
        
        /// <remarks/>
        public string vehicleNumber;
        
        /// <remarks/>
        public int movePurpose;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool movePurposeSpecified;
        
        /// <remarks/>
        public bool fuelInvoice;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuelInvoiceSpecified;
        
        /// <remarks/>
        public int specialInvoiceCategory;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool specialInvoiceCategorySpecified;
        
        /// <remarks/>
        public int invoiceVariationType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invoiceVariationTypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("otherCorrelatedEntities")]
        public EntityType[] otherCorrelatedEntities;
        
        /// <remarks/>
        public OtherDeliveryNoteHeaderType otherDeliveryNoteHeader;
        
        /// <remarks/>
        public bool isDeliveryNote;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDeliveryNoteSpecified;
        
        /// <remarks/>
        public string otherMovePurposeTitle;
        
        /// <remarks/>
        public bool thirdPartyCollection;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thirdPartyCollectionSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum InvoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.1")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.3")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.4")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.5")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.6")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.1")]
        Item21,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.2")]
        Item22,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.3")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.4")]
        Item24,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.1")]
        Item31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3.2")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.1")]
        Item51,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.2")]
        Item52,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6.1")]
        Item61,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6.2")]
        Item62,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7.1")]
        Item71,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8.1")]
        Item81,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8.2")]
        Item82,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8.4")]
        Item84,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8.5")]
        Item85,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8.6")]
        Item86,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9.3")]
        Item93,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.1")]
        Item111,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.2")]
        Item112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.3")]
        Item113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.4")]
        Item114,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11.5")]
        Item115,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item121,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.1")]
        Item131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.2")]
        Item132,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.3")]
        Item133,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.4")]
        Item134,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.30")]
        Item1330,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13.31")]
        Item1331,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.1")]
        Item141,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.2")]
        Item142,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.3")]
        Item143,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.4")]
        Item144,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.5")]
        Item145,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.30")]
        Item1430,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14.31")]
        Item1431,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15.1")]
        Item151,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16.1")]
        Item161,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.1")]
        Item171,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.2")]
        Item172,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.3")]
        Item173,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.4")]
        Item174,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.5")]
        Item175,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17.6")]
        Item176,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum CurrencyType {
        
        /// <remarks/>
        AED,
        
        /// <remarks/>
        AFN,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        AMD,
        
        /// <remarks/>
        ANG,
        
        /// <remarks/>
        AOA,
        
        /// <remarks/>
        ARS,
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        AWG,
        
        /// <remarks/>
        AZN,
        
        /// <remarks/>
        BAM,
        
        /// <remarks/>
        BBD,
        
        /// <remarks/>
        BDT,
        
        /// <remarks/>
        BGN,
        
        /// <remarks/>
        BHD,
        
        /// <remarks/>
        BIF,
        
        /// <remarks/>
        BMD,
        
        /// <remarks/>
        BND,
        
        /// <remarks/>
        BOB,
        
        /// <remarks/>
        BOV,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        BSD,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BWP,
        
        /// <remarks/>
        BYR,
        
        /// <remarks/>
        BZD,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CDF,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        CLF,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        COU,
        
        /// <remarks/>
        CRC,
        
        /// <remarks/>
        CUC,
        
        /// <remarks/>
        CUP,
        
        /// <remarks/>
        CVE,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DJF,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        DOP,
        
        /// <remarks/>
        DZD,
        
        /// <remarks/>
        EEK,
        
        /// <remarks/>
        EGP,
        
        /// <remarks/>
        ERN,
        
        /// <remarks/>
        ETB,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        FJD,
        
        /// <remarks/>
        FKP,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        GEL,
        
        /// <remarks/>
        GHS,
        
        /// <remarks/>
        GIP,
        
        /// <remarks/>
        GMD,
        
        /// <remarks/>
        GNF,
        
        /// <remarks/>
        GTQ,
        
        /// <remarks/>
        GWP,
        
        /// <remarks/>
        GYD,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HNL,
        
        /// <remarks/>
        HRK,
        
        /// <remarks/>
        HTG,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        IQD,
        
        /// <remarks/>
        IRR,
        
        /// <remarks/>
        ISK,
        
        /// <remarks/>
        JMD,
        
        /// <remarks/>
        JOD,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        KES,
        
        /// <remarks/>
        KGS,
        
        /// <remarks/>
        KHR,
        
        /// <remarks/>
        KMF,
        
        /// <remarks/>
        KPW,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        KWD,
        
        /// <remarks/>
        KYD,
        
        /// <remarks/>
        KZT,
        
        /// <remarks/>
        LAK,
        
        /// <remarks/>
        LBP,
        
        /// <remarks/>
        LKR,
        
        /// <remarks/>
        LRD,
        
        /// <remarks/>
        LSL,
        
        /// <remarks/>
        LTL,
        
        /// <remarks/>
        LVL,
        
        /// <remarks/>
        LYD,
        
        /// <remarks/>
        MAD,
        
        /// <remarks/>
        MDL,
        
        /// <remarks/>
        MGA,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MMK,
        
        /// <remarks/>
        MNT,
        
        /// <remarks/>
        MOP,
        
        /// <remarks/>
        MRO,
        
        /// <remarks/>
        MUR,
        
        /// <remarks/>
        MVR,
        
        /// <remarks/>
        MWK,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        MXV,
        
        /// <remarks/>
        MYR,
        
        /// <remarks/>
        MZN,
        
        /// <remarks/>
        NAD,
        
        /// <remarks/>
        NGN,
        
        /// <remarks/>
        NIO,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        OMR,
        
        /// <remarks/>
        PAB,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        PGK,
        
        /// <remarks/>
        PHP,
        
        /// <remarks/>
        PKR,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        PYG,
        
        /// <remarks/>
        QAR,
        
        /// <remarks/>
        RON,
        
        /// <remarks/>
        RSD,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        RWF,
        
        /// <remarks/>
        SAR,
        
        /// <remarks/>
        SBD,
        
        /// <remarks/>
        SCR,
        
        /// <remarks/>
        SDG,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        SHP,
        
        /// <remarks/>
        SLL,
        
        /// <remarks/>
        SOS,
        
        /// <remarks/>
        SRD,
        
        /// <remarks/>
        STD,
        
        /// <remarks/>
        SVC,
        
        /// <remarks/>
        SYP,
        
        /// <remarks/>
        SZL,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TJS,
        
        /// <remarks/>
        TMT,
        
        /// <remarks/>
        TND,
        
        /// <remarks/>
        TOP,
        
        /// <remarks/>
        TRY,
        
        /// <remarks/>
        TTD,
        
        /// <remarks/>
        TVD,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        TZS,
        
        /// <remarks/>
        UAH,
        
        /// <remarks/>
        UGX,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UYU,
        
        /// <remarks/>
        UZS,
        
        /// <remarks/>
        VEF,
        
        /// <remarks/>
        VND,
        
        /// <remarks/>
        VUV,
        
        /// <remarks/>
        WST,
        
        /// <remarks/>
        XAF,
        
        /// <remarks/>
        XCD,
        
        /// <remarks/>
        XOF,
        
        /// <remarks/>
        XPD,
        
        /// <remarks/>
        XPF,
        
        /// <remarks/>
        YER,
        
        /// <remarks/>
        ZAR,
        
        /// <remarks/>
        ZMK,
        
        /// <remarks/>
        ZWL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0", IsNullable=false)]
    public partial class RequestedDoc {
        
        /// <remarks/>
        public continuationTokenType continuationToken;
        
        /// <remarks/>
        public RequestedDocInvoicesDoc invoicesDoc;
        
        /// <remarks/>
        public RequestedDocCancelledInvoicesDoc cancelledInvoicesDoc;
        
        /// <remarks/>
        public RequestedDocIncomeClassificationsDoc incomeClassificationsDoc;
        
        /// <remarks/>
        public RequestedDocExpensesClassificationsDoc expensesClassificationsDoc;
        
        /// <remarks/>
        public RequestedDocPaymentMethodsDoc paymentMethodsDoc;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocInvoicesDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoice")]
        public AadeBookInvoiceType[] invoice;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocCancelledInvoicesDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cancelledInvoice")]
        public CancelledInvoiceType[] cancelledInvoice;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocIncomeClassificationsDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeInvoiceClassification")]
        public InvoiceIncomeClassificationType[] incomeInvoiceClassification;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocExpensesClassificationsDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesInvoiceClassification")]
        public InvoiceExpensesClassificationType[] expensesInvoiceClassification;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDocPaymentMethodsDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentMethods")]
        public PaymentMethodType[] paymentMethods;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=false)]
    public partial class IncomeClassificationsDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incomeInvoiceClassification")]
        public InvoiceIncomeClassificationType[] incomeInvoiceClassification;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0", IsNullable=false)]
    public partial class ExpensesClassificationsDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expensesInvoiceClassification")]
        public InvoiceExpensesClassificationType[] expensesInvoiceClassification;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0", IsNullable=false)]
    public partial class PaymentMethodsDoc {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentMethods")]
        public PaymentMethodType[] paymentMethods;
    }
}
