//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PaymentMethodDetailType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class PaymentMethodDetailType
    {
        
        /// <summary>
        /// <para>Τύπος Πληρωμής</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 7.</para>
        /// </summary>
        [DescriptionAttribute("Τύπος Πληρωμής")]
        [RangeAttribute(typeof(int), "1", "7")]
        [RequiredAttribute()]
        [XmlElementAttribute("type")]
        public int type { get; set; }
        
        /// <summary>
        /// <para>Αναλογούν Ποσό</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [DescriptionAttribute("Αναλογούν Ποσό")]
        [RequiredAttribute()]
        [XmlElementAttribute("amount")]
        public decimal amount { get; set; }
        
        /// <summary>
        /// <para>Λοιπές Πληροφορίες</para>
        /// </summary>
        [DescriptionAttribute("Λοιπές Πληροφορίες")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("paymentMethodInfo")]
        public string paymentMethodInfo { get; set; }
        
        /// <summary>
        /// <para>Φιλοδώρημα</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [DescriptionAttribute("Φιλοδώρημα")]
        [XmlElementAttribute("tipAmount")]
        public decimal tipAmount { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die tipAmount-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the tipAmount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool tipAmountSpecified { get; set; }
        
        /// <summary>
        /// <para>Μοναδική Ταυτότητα Πληρωμής</para>
        /// </summary>
        [DescriptionAttribute("Μοναδική Ταυτότητα Πληρωμής")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("transactionId")]
        public string transactionId { get; set; }
        
        /// <summary>
        /// <para>Υπογραφή Πληρωμής Παρόχου</para>
        /// </summary>
        [DescriptionAttribute("Υπογραφή Πληρωμής Παρόχου")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("ProvidersSignature")]
        public ProviderSignatureType ProvidersSignature { get; set; }
        
        /// <summary>
        /// <para>Υπογραφή Πληρωμής ΦΗΜ με σύστημα λογισμικού (ERP)</para>
        /// </summary>
        [DescriptionAttribute("Υπογραφή Πληρωμής ΦΗΜ με σύστημα λογισμικού (ERP)")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("ECRToken")]
        public ECRTokenType ECRToken { get; set; }
    }
}
