//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Μέθοδοι Πληρωμής</para>
    /// </summary>
    [DescriptionAttribute("Μέθοδοι Πληρωμής")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PaymentMethodsDoc", Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0", AnonymousType=true)]
    [XmlRootAttribute("PaymentMethodsDoc", Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0")]
    public partial class PaymentMethodsDoc
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("paymentMethods")]
        public List<PaymentMethodType> paymentMethods { get; set; }
    }
}
