//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PaymentMethodType", Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0")]
    public partial class PaymentMethodType
    {
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Καταχώρησης Παραστατικού</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Καταχώρησης Παραστατικού")]
        [RequiredAttribute()]
        [XmlElementAttribute("invoiceMark")]
        public long invoiceMark { get; set; }
        
        /// <summary>
        /// <para>Αποδεικτικό Λήψης Τρόπων Πληρωμής. Συμπληρώνεται από την Υπηρεσία</para>
        /// </summary>
        [DescriptionAttribute("Αποδεικτικό Λήψης Τρόπων Πληρωμής. Συμπληρώνεται από την Υπηρεσία")]
        [XmlElementAttribute("paymentMethodMark")]
        public long paymentMethodMark { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die paymentMethodMark-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the paymentMethodMark property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool paymentMethodMarkSpecified { get; set; }
        
        /// <summary>
        /// <para>ΑΦΜ Οντότητας Αναφοράς</para>
        /// </summary>
        [DescriptionAttribute("ΑΦΜ Οντότητας Αναφοράς")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("entityVatNumber")]
        public string entityVatNumber { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<MyData.Xsd.PaymentMethodDetailType> _paymentMethodDetails;
        
        [RequiredAttribute()]
        [XmlElementAttribute("paymentMethodDetails")]
        public List<MyData.Xsd.PaymentMethodDetailType> paymentMethodDetails
        {
            get
            {
                return _paymentMethodDetails;
            }
            set
            {
                _paymentMethodDetails = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="PaymentMethodType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PaymentMethodType" /> class.</para>
        /// </summary>
        public PaymentMethodType()
        {
            this._paymentMethodDetails = new List<MyData.Xsd.PaymentMethodDetailType>();
        }
    }
}
