//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 
namespace AxMyData.AADE {
    using System.Xml.Serialization;
    
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=false)]
    public partial class IncomeClassificationsDoc {
        
        
        [XmlElement("incomeInvoiceClassification")]
        public InvoiceIncomeClassificationType[] incomeInvoiceClassification;
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class InvoiceIncomeClassificationType {
        
        
        public long invoiceMark;
        
        
        public long classificationMark;
        
        
        [XmlIgnore]
        public bool classificationMarkSpecified;
        
        
        public string entityVatNumber;
        
        
        [XmlElement("invoicesIncomeClassificationDetails", typeof(InvoicesIncomeClassificationDetailType))]
        [XmlElement("transactionMode", typeof(int))]
        public object[] Items;
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class InvoicesIncomeClassificationDetailType {
        
        
        public int lineNumber;
        
        
        [XmlElement("incomeClassificationDetailData")]
        public IncomeClassificationType[] incomeClassificationDetailData;
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [Serializable]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class IncomeClassificationType {
        
        
        public IncomeClassificationValueType classificationType;
        
        
        [XmlIgnore]
        public bool classificationTypeSpecified;
        
        
        public IncomeClassificationCategoryType classificationCategory;
        
        
        public decimal amount;
        
        
        public sbyte id;
        
        
        [XmlIgnore]
        public bool idSpecified;
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [Serializable]
    [XmlType(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public enum IncomeClassificationValueType {
        
        
        E3_106,
        
        
        E3_205,
        
        
        E3_210,
        
        
        E3_305,
        
        
        E3_310,
        
        
        E3_318,
        
        
        E3_561_001,
        
        
        E3_561_002,
        
        
        E3_561_003,
        
        
        E3_561_004,
        
        
        E3_561_005,
        
        
        E3_561_006,
        
        
        E3_561_007,
        
        
        E3_562,
        
        
        E3_563,
        
        
        E3_564,
        
        
        E3_565,
        
        
        E3_566,
        
        
        E3_567,
        
        
        E3_568,
        
        
        E3_570,
        
        
        E3_595,
        
        
        E3_596,
        
        
        E3_597,
        
        
        E3_880_001,
        
        
        E3_880_002,
        
        
        E3_880_003,
        
        
        E3_880_004,
        
        
        E3_881_001,
        
        
        E3_881_002,
        
        
        E3_881_003,
        
        
        E3_881_004,
        
        
        E3_598_001,
        
        
        E3_598_003,
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [Serializable]
    [XmlType(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public enum IncomeClassificationCategoryType {
        
        
        category1_1,
        
        
        category1_2,
        
        
        category1_3,
        
        
        category1_4,
        
        
        category1_5,
        
        
        category1_6,
        
        
        category1_7,
        
        
        category1_8,
        
        
        category1_9,
        
        
        category1_10,
        
        
        category1_95,
        
        
        category3,
    }
}
