//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoiceProviderType", Namespace="")]
    public partial class InvoiceProviderType
    {
        
        /// <summary>
        /// <para>ΑΦΜ Εκδότη</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("issuerVAT")]
        public string issuerVAT { get; set; }
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Καταχώρησης παραστατικού Παρόχου</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("invoiceProviderMark")]
        public long invoiceProviderMark { get; set; }
        
        /// <summary>
        /// <para>Αναγνωριστικό οντότητας</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("invoiceUid")]
        public string invoiceUid { get; set; }
        
        /// <summary>
        /// <para>Συμβολοσειρά Αυθεντικοποίησης Παραστατικού Παρόχου</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("authenticationCode")]
        public string authenticationCode { get; set; }
    }
}
