//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Παραστατικά από Πάροχο</para>
    /// </summary>
    [DescriptionAttribute("Παραστατικά από Πάροχο")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("RequestedProviderDoc", Namespace="", AnonymousType=true)]
    [XmlRootAttribute("RequestedProviderDoc", Namespace="")]
    public partial class RequestedProviderDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<ContinuationTokenType> _continuationToken;
        
        [XmlElementAttribute("continuationToken")]
        public List<ContinuationTokenType> continuationToken
        {
            get
            {
                return _continuationToken;
            }
            set
            {
                _continuationToken = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die continuationToken-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the continuationToken collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool continuationTokenSpecified
        {
            get
            {
                return ((this.continuationToken != null) 
                            && (this.continuationToken.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RequestedProviderDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestedProviderDoc" /> class.</para>
        /// </summary>
        public RequestedProviderDoc()
        {
            this._continuationToken = new List<ContinuationTokenType>();
            this._invoiceProviderType = new List<InvoiceProviderType>();
        }
        
        [XmlIgnoreAttribute()]
        private List<InvoiceProviderType> _invoiceProviderType;
        
        [XmlElementAttribute("InvoiceProviderType")]
        public List<InvoiceProviderType> InvoiceProviderType
        {
            get
            {
                return _invoiceProviderType;
            }
            set
            {
                _invoiceProviderType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die InvoiceProviderType-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the InvoiceProviderType collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceProviderTypeSpecified
        {
            get
            {
                return ((this.InvoiceProviderType != null) 
                            && (this.InvoiceProviderType.Count != 0));
            }
        }
    }
}
