// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.41979 MIT License (MIT) 
//    <NameSpace>MyDataXsd</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>True</GenerateSeparateFiles><OutputFilePath>expensesClassification-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataXsd {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("ExpensesClassificationValueType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0", IsNullable=false)]
    public enum ExpensesClassificationTypeClassificationType {
        
        /// <remarks/>
        E3_101,
        
        /// <remarks/>
        E3_102_001,
        
        /// <remarks/>
        E3_102_002,
        
        /// <remarks/>
        E3_102_003,
        
        /// <remarks/>
        E3_102_004,
        
        /// <remarks/>
        E3_102_005,
        
        /// <remarks/>
        E3_102_006,
        
        /// <remarks/>
        E3_104,
        
        /// <remarks/>
        E3_201,
        
        /// <remarks/>
        E3_202_001,
        
        /// <remarks/>
        E3_202_002,
        
        /// <remarks/>
        E3_202_003,
        
        /// <remarks/>
        E3_202_004,
        
        /// <remarks/>
        E3_202_005,
        
        /// <remarks/>
        E3_204,
        
        /// <remarks/>
        E3_207,
        
        /// <remarks/>
        E3_209,
        
        /// <remarks/>
        E3_301,
        
        /// <remarks/>
        E3_302_001,
        
        /// <remarks/>
        E3_302_002,
        
        /// <remarks/>
        E3_302_003,
        
        /// <remarks/>
        E3_302_004,
        
        /// <remarks/>
        E3_302_005,
        
        /// <remarks/>
        E3_304,
        
        /// <remarks/>
        E3_307,
        
        /// <remarks/>
        E3_309,
        
        /// <remarks/>
        E3_312,
        
        /// <remarks/>
        E3_313_001,
        
        /// <remarks/>
        E3_313_002,
        
        /// <remarks/>
        E3_313_003,
        
        /// <remarks/>
        E3_313_004,
        
        /// <remarks/>
        E3_313_005,
        
        /// <remarks/>
        E3_315,
        
        /// <remarks/>
        E3_581_001,
        
        /// <remarks/>
        E3_581_002,
        
        /// <remarks/>
        E3_581_003,
        
        /// <remarks/>
        E3_582,
        
        /// <remarks/>
        E3_583,
        
        /// <remarks/>
        E3_584,
        
        /// <remarks/>
        E3_585_001,
        
        /// <remarks/>
        E3_585_002,
        
        /// <remarks/>
        E3_585_003,
        
        /// <remarks/>
        E3_585_004,
        
        /// <remarks/>
        E3_585_005,
        
        /// <remarks/>
        E3_585_006,
        
        /// <remarks/>
        E3_585_007,
        
        /// <remarks/>
        E3_585_008,
        
        /// <remarks/>
        E3_585_009,
        
        /// <remarks/>
        E3_585_010,
        
        /// <remarks/>
        E3_585_011,
        
        /// <remarks/>
        E3_585_012,
        
        /// <remarks/>
        E3_585_013,
        
        /// <remarks/>
        E3_585_014,
        
        /// <remarks/>
        E3_585_015,
        
        /// <remarks/>
        E3_585_016,
        
        /// <remarks/>
        E3_586,
        
        /// <remarks/>
        E3_587,
        
        /// <remarks/>
        E3_588,
        
        /// <remarks/>
        E3_589,
        
        /// <remarks/>
        E3_881_001,
        
        /// <remarks/>
        E3_881_002,
        
        /// <remarks/>
        E3_881_003,
        
        /// <remarks/>
        E3_881_004,
        
        /// <remarks/>
        E3_882_001,
        
        /// <remarks/>
        E3_882_002,
        
        /// <remarks/>
        E3_882_003,
        
        /// <remarks/>
        E3_882_004,
        
        /// <remarks/>
        E3_883_001,
        
        /// <remarks/>
        E3_883_002,
        
        /// <remarks/>
        E3_883_003,
        
        /// <remarks/>
        E3_883_004,
        
        /// <remarks/>
        VAT_361,
        
        /// <remarks/>
        VAT_362,
        
        /// <remarks/>
        VAT_363,
        
        /// <remarks/>
        VAT_364,
        
        /// <remarks/>
        VAT_365,
        
        /// <remarks/>
        VAT_366,
        
        /// <remarks/>
        E3_103,
        
        /// <remarks/>
        E3_203,
        
        /// <remarks/>
        E3_303,
        
        /// <remarks/>
        E3_208,
        
        /// <remarks/>
        E3_308,
        
        /// <remarks/>
        E3_314,
        
        /// <remarks/>
        E3_106,
        
        /// <remarks/>
        E3_205,
        
        /// <remarks/>
        E3_305,
        
        /// <remarks/>
        E3_210,
        
        /// <remarks/>
        E3_310,
        
        /// <remarks/>
        E3_318,
        
        /// <remarks/>
        E3_598_002,
    }
}
