//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("AddressType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class AddressType
    {
        
        /// <summary>
        /// <para>Όνομα</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [MaxLengthAttribute(150)]
        [XmlElementAttribute("street")]
        public string street { get; set; }
        
        /// <summary>
        /// <para>Αριθμός</para>
        /// </summary>
        [DescriptionAttribute("Αριθμός")]
        [XmlElementAttribute("number")]
        public string number { get; set; }
        
        /// <summary>
        /// <para>ΤΚ</para>
        /// </summary>
        [DescriptionAttribute("ΤΚ")]
        [RequiredAttribute()]
        [XmlElementAttribute("postalCode")]
        public string postalCode { get; set; }
        
        /// <summary>
        /// <para>Πόλη</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [MaxLengthAttribute(150)]
        [RequiredAttribute()]
        [XmlElementAttribute("city")]
        public string city { get; set; }
    }
}
