//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CountryType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum CountryType
    {
        
        AD,
        
        AE,
        
        AF,
        
        AG,
        
        AI,
        
        AL,
        
        AM,
        
        AN,
        
        AO,
        
        AQ,
        
        AR,
        
        AS,
        
        AT,
        
        AU,
        
        AW,
        
        AX,
        
        AZ,
        
        BA,
        
        BB,
        
        BD,
        
        BE,
        
        BF,
        
        BG,
        
        BH,
        
        BI,
        
        BJ,
        
        BL,
        
        BM,
        
        BN,
        
        BO,
        
        BR,
        
        BS,
        
        BT,
        
        BV,
        
        BW,
        
        BY,
        
        BZ,
        
        CA,
        
        CC,
        
        CD,
        
        CF,
        
        CG,
        
        CH,
        
        CI,
        
        CK,
        
        CL,
        
        CM,
        
        CN,
        
        CO,
        
        CR,
        
        CU,
        
        CV,
        
        CX,
        
        CY,
        
        CZ,
        
        DE,
        
        DJ,
        
        DK,
        
        DM,
        
        DO,
        
        DZ,
        
        EC,
        
        EE,
        
        EG,
        
        EH,
        
        ER,
        
        ES,
        
        ET,
        
        FI,
        
        FJ,
        
        FK,
        
        FM,
        
        FO,
        
        FR,
        
        GA,
        
        GB,
        
        GD,
        
        GE,
        
        GF,
        
        GG,
        
        GH,
        
        GI,
        
        GL,
        
        GM,
        
        GN,
        
        GP,
        
        GQ,
        
        GR,
        
        GS,
        
        GT,
        
        GU,
        
        GW,
        
        GY,
        
        HK,
        
        HM,
        
        HN,
        
        HR,
        
        HT,
        
        HU,
        
        ID,
        
        IE,
        
        IL,
        
        IM,
        
        IN,
        
        IO,
        
        IQ,
        
        IR,
        
        IS,
        
        IT,
        
        JE,
        
        JM,
        
        JO,
        
        JP,
        
        KE,
        
        KG,
        
        KH,
        
        KI,
        
        KM,
        
        KN,
        
        KP,
        
        KR,
        
        KW,
        
        KY,
        
        KZ,
        
        LA,
        
        LB,
        
        LC,
        
        LI,
        
        LK,
        
        LR,
        
        LS,
        
        LT,
        
        LU,
        
        LV,
        
        LY,
        
        MA,
        
        MC,
        
        MD,
        
        ME,
        
        MF,
        
        MG,
        
        MH,
        
        MK,
        
        ML,
        
        MM,
        
        MN,
        
        MO,
        
        MP,
        
        MQ,
        
        MR,
        
        MS,
        
        MT,
        
        MU,
        
        MV,
        
        MW,
        
        MX,
        
        MY,
        
        MZ,
        
        NA,
        
        NC,
        
        NE,
        
        NF,
        
        NG,
        
        NI,
        
        NL,
        
        NO,
        
        NP,
        
        NR,
        
        NU,
        
        NZ,
        
        OC,
        
        OM,
        
        PA,
        
        PE,
        
        PF,
        
        PG,
        
        PH,
        
        PK,
        
        PL,
        
        PM,
        
        PN,
        
        PR,
        
        PS,
        
        PT,
        
        PW,
        
        PY,
        
        QA,
        
        RE,
        
        RO,
        
        RS,
        
        RU,
        
        RW,
        
        SA,
        
        SB,
        
        SC,
        
        SD,
        
        SE,
        
        SG,
        
        SH,
        
        SI,
        
        SJ,
        
        SK,
        
        SL,
        
        SM,
        
        SN,
        
        SO,
        
        SR,
        
        ST,
        
        SV,
        
        SY,
        
        SZ,
        
        TC,
        
        TD,
        
        TF,
        
        TG,
        
        TH,
        
        TJ,
        
        TK,
        
        TL,
        
        TM,
        
        TN,
        
        TO,
        
        TR,
        
        TT,
        
        TV,
        
        TW,
        
        TZ,
        
        UA,
        
        UG,
        
        UM,
        
        US,
        
        UY,
        
        UZ,
        
        VA,
        
        VC,
        
        VE,
        
        VG,
        
        VI,
        
        VN,
        
        VU,
        
        WF,
        
        WS,
        
        YE,
        
        YT,
        
        ZA,
        
        ZM,
        
        ZW,
    }
}
