//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ECRTokenType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ECRTokenType
    {
        
        /// <summary>
        /// <para>ECR id: Αριθμός μητρώου του φορολογικού μηχανισμού</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [DescriptionAttribute("ECR id: Αριθμός μητρώου του φορολογικού μηχανισμού")]
        [MaxLengthAttribute(15)]
        [RequiredAttribute()]
        [XmlElementAttribute("SigningAuthor")]
        public string SigningAuthor { get; set; }

        /// <summary>
        /// <para>Μοναδικός 6-ψήφιος κωδικός που χαρακτηρίζει την κάθε συναλλαγή</para>
        /// <para xml:lang="en">Minimum length: 6.</para>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// <para>Λεπτομέρειες στην υπ’ αριθμ. Α. 1155/09-10-2023 απόφαση (ΦΕΚ 5992 Β΄/13.10.2023), όπως ισχύει</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός 6-ψήφιος κωδικός που χαρακτηρίζει την κάθε συναλλαγή")]
        [MinLengthAttribute(6)]
        [MaxLengthAttribute(6)]
        [RequiredAttribute()]
        [XmlElementAttribute("SessionNumber")]
        public string SessionNumber { get; set; }
    }
}
