//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoiceHeaderType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceHeaderType
    {
        
        /// <summary>
        /// <para>Σειρά Παραστατικού</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [MaxLengthAttribute(50)]
        [RequiredAttribute()]
        [XmlElementAttribute("series")]
        public string series { get; set; }
        
        /// <summary>
        /// <para>ΑΑ Παραστατικού</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [MaxLengthAttribute(50)]
        [RequiredAttribute()]
        [XmlElementAttribute("aa")]
        public string aa { get; set; }
        
        /// <summary>
        /// <para>Ημερομηνία Έκδοσης</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("issueDate", DataType="date")]
        public DateTime issueDate { get; set; }
        
        /// <summary>
        /// <para>Είδος Παραστατικού</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("invoiceType")]
        public InvoiceType invoiceType { get; set; }
        
        /// <summary>
        /// <para>Αναστολή Καταβολής ΦΠΑ</para>
        /// </summary>
        [XmlElementAttribute("vatPaymentSuspension")]
        public Nullable<bool> vatPaymentSuspension { get; set; }
        
        /// <summary>
        /// <para>Νόμισμα</para>
        /// </summary>
        [XmlElementAttribute("currency")]
        public Nullable<CurrencyType> currency { get; set; }
        
        /// <summary>
        /// <para>Ισοτιμία</para>
        /// <para xml:lang="en">Minimum exclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 5.</para>
        /// <para xml:lang="en">Maximum inclusive value: 50000.</para>
        /// </summary>
        [XmlElementAttribute("exchangeRate")]
        public Nullable<decimal> exchangeRate { get; set; }
        
        /// <summary>
        /// <para>Συσχετιζόμενα Παραστατικά</para>
        /// </summary>
        [XmlElementAttribute("correlatedInvoices")]
        public List<long> correlatedInvoices { get; set; }
        
        /// <summary>
        /// <para>Ένδειξη Αυτοτιμολόγησης</para>
        /// </summary>
        [XmlElementAttribute("selfPricing")]
        public Nullable<bool> selfPricing { get; set; }
        
        /// <summary>
        /// <para>Ημερομηνία  Έναρξης Αποστολής</para>
        /// </summary>
        [XmlElementAttribute("dispatchDate", DataType="date")]
        public Nullable<DateTime> dispatchDate { get; set; }
        
        /// <summary>
        /// <para>Ώρα Έναρξης Αποστολής</para>
        /// </summary>
        [XmlElementAttribute("dispatchTime", DataType="time")]
        public Nullable<DateTime> dispatchTime { get; set; }
        
        /// <summary>
        /// <para>Αριθμός Οχήματος</para>
        /// <para>Αριθμός Μεταφορικού Μέσου</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [MaxLengthAttribute(150)]
        [XmlElementAttribute("vehicleNumber")]
        public string vehicleNumber { get; set; }
        
        /// <summary>
        /// <para>Σκοπός Διακίνησης</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 19.</para>
        /// </summary>
        [RangeAttribute(typeof(int), "1", "19")]
        [XmlElementAttribute("movePurpose")]
        public Nullable<int> movePurpose { get; set; }
        
        /// <summary>
        /// <para>Παραστατικό Καυσίμων</para>
        /// </summary>
        [XmlElementAttribute("fuelInvoice")]
        public Nullable<bool> fuelInvoice { get; set; }
        
        /// <summary>
        /// <para>Ειδική Κατηγορία Παραστατικού</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 12.</para>
        /// </summary>
        [RangeAttribute(typeof(int), "1", "12")]
        [XmlElementAttribute("specialInvoiceCategory")]
        public Nullable<int> specialInvoiceCategory { get; set; }
        
        /// <summary>
        /// <para>Τύπος Απόκλισης Παραστατικού</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 4.</para>
        /// </summary>
        [RangeAttribute(typeof(int), "1", "4")]
        [XmlElementAttribute("invoiceVariationType")]
        public Nullable<int> invoiceVariationType { get; set; }
        
        /// <summary>
        /// <para>Λοιπές συσχετιζόμενες οντοτήτες</para>
        /// </summary>
        [XmlElementAttribute("otherCorrelatedEntities")]
        public List<EntityType> otherCorrelatedEntities { get; set; }
        
        /// <summary>
        /// <para>Λοιπά Γενικά Στοιχεία Διακίνησης</para>
        /// </summary>
        [XmlElementAttribute("otherDeliveryNoteHeader")]
        public OtherDeliveryNoteHeaderType otherDeliveryNoteHeader { get; set; }
        
        /// <summary>
        /// <para>Ένδειξη Παραστατικού Διακίνησης</para>
        /// </summary>
        [XmlElementAttribute("isDeliveryNote")]
        public Nullable<bool> isDeliveryNote { get; set; }
        
        /// <summary>
        /// <para>Τίτλος της Λοιπής Αιτίας Διακίνησης</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [MaxLengthAttribute(150)]
        [XmlElementAttribute("otherMovePurposeTitle")]
        public string otherMovePurposeTitle { get; set; }
        
        /// <summary>
        /// <para>Ένδειξη Εισπράξης Τρίτων</para>
        /// </summary>
        [XmlElementAttribute("thirdPartyCollection")]
        public Nullable<bool> thirdPartyCollection { get; set; }
    }
}
