//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoiceSummaryType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceSummaryType
    {
        
        /// <summary>
        /// <para>Σύνολο Καθαρής Αξίας</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalNetValue")]
        public decimal totalNetValue { get; set; }
        
        /// <summary>
        /// <para>Σύνολο ΦΠΑ</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalVatAmount")]
        public decimal totalVatAmount { get; set; }
        
        /// <summary>
        /// <para>Σύνολο Παρ. Φόρων</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalWithheldAmount")]
        public decimal totalWithheldAmount { get; set; }
        
        /// <summary>
        /// <para>Σύνολο Τελών</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalFeesAmount")]
        public decimal totalFeesAmount { get; set; }
        
        /// <summary>
        /// <para>Σύνολο Χαρτοσήμου</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalStampDutyAmount")]
        public decimal totalStampDutyAmount { get; set; }
        
        /// <summary>
        /// <para>Σύνολο Λοιπών Φόρων</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalOtherTaxesAmount")]
        public decimal totalOtherTaxesAmount { get; set; }
        
        /// <summary>
        /// <para>Σύνολο Κρατήσεων</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalDeductionsAmount")]
        public decimal totalDeductionsAmount { get; set; }
        
        /// <summary>
        /// <para>Συνολική Αξία</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("totalGrossValue")]
        public decimal totalGrossValue { get; set; }
        
        /// <summary>
        /// <para>Λίστα Χαρακτηρισμών Εσόδων</para>
        /// </summary>
        [XmlElementAttribute("incomeClassification")]
        public List<MyData.Xsd.IncomeClassificationType> incomeClassification { get; set; }
        
        [XmlElementAttribute("expensesClassification")]
        public List<MyData.Xsd.ExpensesClassificationType> expensesClassification { get; set; }
    }
}
