//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoiceType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public enum InvoiceType
    {
        
        [XmlEnumAttribute("1.1")]
        Item1Period1,
        
        [XmlEnumAttribute("1.2")]
        Item1Period2,
        
        [XmlEnumAttribute("1.3")]
        Item1Period3,
        
        [XmlEnumAttribute("1.4")]
        Item1Period4,
        
        [XmlEnumAttribute("1.5")]
        Item1Period5,
        
        [XmlEnumAttribute("1.6")]
        Item1Period6,
        
        [XmlEnumAttribute("2.1")]
        Item2Period1,
        
        [XmlEnumAttribute("2.2")]
        Item2Period2,
        
        [XmlEnumAttribute("2.3")]
        Item2Period3,
        
        [XmlEnumAttribute("2.4")]
        Item2Period4,
        
        [XmlEnumAttribute("3.1")]
        Item3Period1,
        
        [XmlEnumAttribute("3.2")]
        Item3Period2,
        
        [XmlEnumAttribute("4")]
        Item4,
        
        [XmlEnumAttribute("5.1")]
        Item5Period1,
        
        [XmlEnumAttribute("5.2")]
        Item5Period2,
        
        [XmlEnumAttribute("6.1")]
        Item6Period1,
        
        [XmlEnumAttribute("6.2")]
        Item6Period2,
        
        [XmlEnumAttribute("7.1")]
        Item7Period1,
        
        [XmlEnumAttribute("8.1")]
        Item8Period1,
        
        [XmlEnumAttribute("8.2")]
        Item8Period2,
        
        [XmlEnumAttribute("8.4")]
        Item8Period4,
        
        [XmlEnumAttribute("8.5")]
        Item8Period5,
        
        [XmlEnumAttribute("8.6")]
        Item8Period6,
        
        [XmlEnumAttribute("9.3")]
        Item9Period3,
        
        [XmlEnumAttribute("11.1")]
        Item11Period1,
        
        [XmlEnumAttribute("11.2")]
        Item11Period2,
        
        [XmlEnumAttribute("11.3")]
        Item11Period3,
        
        [XmlEnumAttribute("11.4")]
        Item11Period4,
        
        [XmlEnumAttribute("11.5")]
        Item11Period5,
        
        [XmlEnumAttribute("12")]
        Item12,
        
        [XmlEnumAttribute("13.1")]
        Item13Period1,
        
        [XmlEnumAttribute("13.2")]
        Item13Period2,
        
        [XmlEnumAttribute("13.3")]
        Item13Period3,
        
        [XmlEnumAttribute("13.4")]
        Item13Period4,
        
        [XmlEnumAttribute("13.30")]
        Item13Period30,
        
        [XmlEnumAttribute("13.31")]
        Item13Period31,
        
        [XmlEnumAttribute("14.1")]
        Item14Period1,
        
        [XmlEnumAttribute("14.2")]
        Item14Period2,
        
        [XmlEnumAttribute("14.3")]
        Item14Period3,
        
        [XmlEnumAttribute("14.4")]
        Item14Period4,
        
        [XmlEnumAttribute("14.5")]
        Item14Period5,
        
        [XmlEnumAttribute("14.30")]
        Item14Period30,
        
        [XmlEnumAttribute("14.31")]
        Item14Period31,
        
        [XmlEnumAttribute("15.1")]
        Item15Period1,
        
        [XmlEnumAttribute("16.1")]
        Item16Period1,
        
        [XmlEnumAttribute("17.1")]
        Item17Period1,
        
        [XmlEnumAttribute("17.2")]
        Item17Period2,
        
        [XmlEnumAttribute("17.3")]
        Item17Period3,
        
        [XmlEnumAttribute("17.4")]
        Item17Period4,
        
        [XmlEnumAttribute("17.5")]
        Item17Period5,
        
        [XmlEnumAttribute("17.6")]
        Item17Period6,
    }
}
