//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Παραστατικό ΑΑΔΕ</para>
    /// </summary>
    [DescriptionAttribute("Παραστατικό ΑΑΔΕ")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoicesDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0", AnonymousType=true)]
    [XmlRootAttribute("InvoicesDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoicesDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<AadeBookInvoiceType> _invoice;
        
        [RequiredAttribute()]
        [XmlElementAttribute("invoice")]
        public List<AadeBookInvoiceType> invoice
        {
            get
            {
                return _invoice;
            }
            set
            {
                _invoice = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="InvoicesDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="InvoicesDoc" /> class.</para>
        /// </summary>
        public InvoicesDoc()
        {
            this._invoice = new List<AadeBookInvoiceType>();
        }
    }
}
