//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoiceHeaderType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class InvoiceHeaderType
    {
        
        /// <summary>
        /// <para>Σειρά Παραστατικού</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [DescriptionAttribute("Σειρά Παραστατικού")]
        [MaxLengthAttribute(50)]
        [RequiredAttribute()]
        [XmlElementAttribute("series")]
        public string series { get; set; }
        
        /// <summary>
        /// <para>ΑΑ Παραστατικού</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [DescriptionAttribute("ΑΑ Παραστατικού")]
        [MaxLengthAttribute(50)]
        [RequiredAttribute()]
        [XmlElementAttribute("aa")]
        public string aa { get; set; }
        
        /// <summary>
        /// <para>Ημερομηνία Έκδοσης</para>
        /// </summary>
        [DescriptionAttribute("Ημερομηνία Έκδοσης")]
        [RequiredAttribute()]
        [XmlElementAttribute("issueDate", DataType="date")]
        public DateTime issueDate { get; set; }
        
        /// <summary>
        /// <para>Είδος Παραστατικού</para>
        /// </summary>
        [DescriptionAttribute("Είδος Παραστατικού")]
        [RequiredAttribute()]
        [XmlElementAttribute("invoiceType")]
        public InvoiceType invoiceType { get; set; }
        
        /// <summary>
        /// <para>Αναστολή Καταβολής ΦΠΑ</para>
        /// </summary>
        [DescriptionAttribute("Αναστολή Καταβολής ΦΠΑ")]
        [XmlElementAttribute("vatPaymentSuspension")]
        public bool vatPaymentSuspension { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die vatPaymentSuspension-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the vatPaymentSuspension property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool vatPaymentSuspensionSpecified { get; set; }
        
        /// <summary>
        /// <para>Νόμισμα</para>
        /// </summary>
        [DescriptionAttribute("Νόμισμα")]
        [XmlElementAttribute("currency")]
        public CurrencyType currency { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die currency-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the currency property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool currencySpecified { get; set; }
        
        /// <summary>
        /// <para>Ισοτιμία</para>
        /// <para xml:lang="en">Minimum exclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 5.</para>
        /// <para xml:lang="en">Maximum inclusive value: 50000.</para>
        /// </summary>
        [DescriptionAttribute("Ισοτιμία")]
        [XmlElementAttribute("exchangeRate")]
        public decimal exchangeRate { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die exchangeRate-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the exchangeRate property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool exchangeRateSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<long> _correlatedInvoices;
        
        /// <summary>
        /// <para>Συσχετιζόμενα Παραστατικά</para>
        /// </summary>
        [DescriptionAttribute("Συσχετιζόμενα Παραστατικά")]
        [XmlElementAttribute("correlatedInvoices")]
        public List<long> correlatedInvoices
        {
            get
            {
                return _correlatedInvoices;
            }
            set
            {
                _correlatedInvoices = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die correlatedInvoices-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the correlatedInvoices collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool correlatedInvoicesSpecified
        {
            get
            {
                return ((this.correlatedInvoices != null) 
                            && (this.correlatedInvoices.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="InvoiceHeaderType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="InvoiceHeaderType" /> class.</para>
        /// </summary>
        public InvoiceHeaderType()
        {
            this._correlatedInvoices = new List<long>();
            this._otherCorrelatedEntities = new List<EntityType>();
        }
        
        /// <summary>
        /// <para>Ένδειξη Αυτοτιμολόγησης</para>
        /// </summary>
        [DescriptionAttribute("Ένδειξη Αυτοτιμολόγησης")]
        [XmlElementAttribute("selfPricing")]
        public bool selfPricing { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die selfPricing-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the selfPricing property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool selfPricingSpecified { get; set; }
        
        /// <summary>
        /// <para>Ημερομηνία  Έναρξης Αποστολής</para>
        /// </summary>
        [DescriptionAttribute("Ημερομηνία Έναρξης Αποστολής")]
        [XmlElementAttribute("dispatchDate", DataType="date")]
        public DateTime dispatchDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die dispatchDate-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the dispatchDate property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool dispatchDateSpecified { get; set; }
        
        /// <summary>
        /// <para>Ώρα Έναρξης Αποστολής</para>
        /// </summary>
        [DescriptionAttribute("Ώρα Έναρξης Αποστολής")]
        [XmlElementAttribute("dispatchTime", DataType="time")]
        public DateTime dispatchTime { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die dispatchTime-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the dispatchTime property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool dispatchTimeSpecified { get; set; }
        
        /// <summary>
        /// <para>Αριθμός Οχήματος</para>
        /// <para>Αριθμός Μεταφορικού Μέσου</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [DescriptionAttribute("Αριθμός Οχήματος")]
        [MaxLengthAttribute(150)]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("vehicleNumber")]
        public string vehicleNumber { get; set; }
        
        /// <summary>
        /// <para>Σκοπός Διακίνησης</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 19.</para>
        /// </summary>
        [DescriptionAttribute("Σκοπός Διακίνησης")]
        [RangeAttribute(typeof(int), "1", "19")]
        [XmlElementAttribute("movePurpose")]
        public int movePurpose { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die movePurpose-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the movePurpose property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool movePurposeSpecified { get; set; }
        
        /// <summary>
        /// <para>Παραστατικό Καυσίμων</para>
        /// </summary>
        [DescriptionAttribute("Παραστατικό Καυσίμων")]
        [XmlElementAttribute("fuelInvoice")]
        public bool fuelInvoice { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die fuelInvoice-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the fuelInvoice property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool fuelInvoiceSpecified { get; set; }
        
        /// <summary>
        /// <para>Ειδική Κατηγορία Παραστατικού</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 12.</para>
        /// </summary>
        [DescriptionAttribute("Ειδική Κατηγορία Παραστατικού")]
        [RangeAttribute(typeof(int), "1", "12")]
        [XmlElementAttribute("specialInvoiceCategory")]
        public int specialInvoiceCategory { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die specialInvoiceCategory-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the specialInvoiceCategory property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool specialInvoiceCategorySpecified { get; set; }
        
        /// <summary>
        /// <para>Τύπος Απόκλισης Παραστατικού</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 4.</para>
        /// </summary>
        [DescriptionAttribute("Τύπος Απόκλισης Παραστατικού")]
        [RangeAttribute(typeof(int), "1", "4")]
        [XmlElementAttribute("invoiceVariationType")]
        public int invoiceVariationType { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die invoiceVariationType-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the invoiceVariationType property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool invoiceVariationTypeSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<EntityType> _otherCorrelatedEntities;
        
        /// <summary>
        /// <para>Λοιπές συσχετιζόμενες οντοτήτες</para>
        /// </summary>
        [DescriptionAttribute("Λοιπές συσχετιζόμενες οντοτήτες")]
        [XmlElementAttribute("otherCorrelatedEntities")]
        public List<EntityType> otherCorrelatedEntities
        {
            get
            {
                return _otherCorrelatedEntities;
            }
            set
            {
                _otherCorrelatedEntities = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die otherCorrelatedEntities-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the otherCorrelatedEntities collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool otherCorrelatedEntitiesSpecified
        {
            get
            {
                return ((this.otherCorrelatedEntities != null) 
                            && (this.otherCorrelatedEntities.Count != 0));
            }
        }
        
        /// <summary>
        /// <para>Λοιπά Γενικά Στοιχεία Διακίνησης</para>
        /// </summary>
        [DescriptionAttribute("Λοιπά Γενικά Στοιχεία Διακίνησης")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("otherDeliveryNoteHeader")]
        public OtherDeliveryNoteHeaderType otherDeliveryNoteHeader { get; set; }
        
        /// <summary>
        /// <para>Ένδειξη Παραστατικού Διακίνησης</para>
        /// </summary>
        [DescriptionAttribute("Ένδειξη Παραστατικού Διακίνησης")]
        [XmlElementAttribute("isDeliveryNote")]
        public bool isDeliveryNote { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die isDeliveryNote-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the isDeliveryNote property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool isDeliveryNoteSpecified { get; set; }
        
        /// <summary>
        /// <para>Τίτλος της Λοιπής Αιτίας Διακίνησης</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [DescriptionAttribute("Τίτλος της Λοιπής Αιτίας Διακίνησης")]
        [MaxLengthAttribute(150)]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("otherMovePurposeTitle")]
        public string otherMovePurposeTitle { get; set; }
        
        /// <summary>
        /// <para>Ένδειξη Εισπράξης Τρίτων</para>
        /// </summary>
        [DescriptionAttribute("Ένδειξη Εισπράξης Τρίτων")]
        [XmlElementAttribute("thirdPartyCollection")]
        public bool thirdPartyCollection { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die thirdPartyCollection-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the thirdPartyCollection property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool thirdPartyCollectionSpecified { get; set; }
    }
}
