//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("OtherDeliveryNoteHeaderType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class OtherDeliveryNoteHeaderType
    {
        
        /// <summary>
        /// <para>Διεύθυνση Φόρτωσης</para>
        /// </summary>
        [DescriptionAttribute("Διεύθυνση Φόρτωσης")]
        [RequiredAttribute()]
        [XmlElementAttribute("loadingAddress")]
        public AddressType loadingAddress { get; set; }
        
        /// <summary>
        /// <para>Διεύθυνση Παράδοσης</para>
        /// </summary>
        [DescriptionAttribute("Διεύθυνση Παράδοσης")]
        [RequiredAttribute()]
        [XmlElementAttribute("deliveryAddress")]
        public AddressType deliveryAddress { get; set; }
        
        /// <summary>
        /// <para>Εγκατάσταση έναρξης διακίνησης (Εκδότη)</para>
        /// </summary>
        [DescriptionAttribute("Εγκατάσταση έναρξης διακίνησης (Εκδότη)")]
        [XmlElementAttribute("startShippingBranch")]
        public Nullable<int> startShippingBranch { get; set; }
        
        /// <summary>
        /// <para>Εγκατάσταση ολοκλήρωσης διακίνησης (Λήπτη)</para>
        /// </summary>
        [DescriptionAttribute("Εγκατάσταση ολοκλήρωσης διακίνησης (Λήπτη)")]
        [XmlElementAttribute("completeShippingBranch")]
        public Nullable<int> completeShippingBranch { get; set; }
    }
}
