//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PartyType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class PartyType
    {
        
        /// <summary>
        /// <para>ΑΦΜ</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [MaxLengthAttribute(30)]
        [RequiredAttribute()]
        [XmlElementAttribute("vatNumber")]
        public string vatNumber { get; set; }
        
        /// <summary>
        /// <para>Κωδ. Χώρας</para>
        /// </summary>
        [DescriptionAttribute("Κωδ. Χώρας")]
        [RequiredAttribute()]
        [XmlElementAttribute("country")]
        public CountryType country { get; set; }
        
        /// <summary>
        /// <para>Αρ. Εγκατάστασης</para>
        /// </summary>
        [DescriptionAttribute("Αρ. Εγκατάστασης")]
        [RequiredAttribute()]
        [XmlElementAttribute("branch")]
        public int branch { get; set; }
        
        /// <summary>
        /// <para>Επωνυμία</para>
        /// <para xml:lang="en">Maximum length: 200.</para>
        /// </summary>
        [MaxLengthAttribute(200)]
        [XmlElementAttribute("name")]
        public string name { get; set; }
        
        /// <summary>
        /// <para>Διεύθυνση</para>
        /// </summary>
        [DescriptionAttribute("Διεύθυνση")]
        [XmlElementAttribute("address")]
        public AddressType address { get; set; }
        
        /// <summary>
        /// <para>Αριθμός επίσημου εγγράφου</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [MaxLengthAttribute(100)]
        [XmlElementAttribute("documentIdNo")]
        public string documentIdNo { get; set; }
        
        /// <summary>
        /// <para>Αρ. Παροχής Ηλ. Ρεύματος</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [DescriptionAttribute("Αρ. Παροχής Ηλ. Ρεύματος")]
        [MaxLengthAttribute(100)]
        [XmlElementAttribute("supplyAccountNo")]
        public string supplyAccountNo { get; set; }
        
        /// <summary>
        /// <para>Κωδ. Χώρας Έκδοσης Επίσημου Εγγράφου</para>
        /// </summary>
        [DescriptionAttribute("Κωδ. Χώρας Έκδοσης Επίσημου Εγγράφου")]
        [XmlElementAttribute("countryDocumentId")]
        public Nullable<CountryType> countryDocumentId { get; set; }
    }
}
