//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProviderSignatureType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ProviderSignatureType
    {
        
        /// <summary>
        /// <para>Provider’s Id</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [DescriptionAttribute("Provider’s Id")]
        [MaxLengthAttribute(20)]
        [RequiredAttribute()]
        [XmlElementAttribute("SigningAuthor")]
        public string SigningAuthor { get; set; }

        /// <summary>
        /// <para>Υπογραφή</para>
        /// <para>Λεπτομέρειες στην υπ’ αριθμ. Α. 1155/09-10-2023 απόφαση (ΦΕΚ 5992 Β΄/13.10.2023), όπως ισχύει</para>
        /// </summary>
        [DescriptionAttribute("Υπογραφή")]
        [RequiredAttribute()]
        [XmlElementAttribute("Signature")]
        public string Signature { get; set; }
    }
}
