//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ShipType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ShipType
    {
        
        /// <summary>
        /// <para>Αριθμός Δήλωσης διενέργειας δραστηριότητας</para>
        /// </summary>
        [DescriptionAttribute("Αριθμός Δήλωσης διενέργειας δραστηριότητας")]
        [RequiredAttribute()]
        [XmlElementAttribute("applicationId")]
        public string applicationId { get; set; }
        
        /// <summary>
        /// <para>Ημερομηνία Δήλωσης</para>
        /// </summary>
        [DescriptionAttribute("Ημερομηνία Δήλωσης")]
        [RequiredAttribute()]
        [XmlElementAttribute("applicationDate", DataType="date")]
        public DateTime applicationDate { get; set; }
        
        /// <summary>
        /// <para>ΔΟΥ Δήλωσης</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [MaxLengthAttribute(150)]
        [XmlElementAttribute("doy")]
        public string doy { get; set; }
        
        /// <summary>
        /// <para>Στοιχεία Πλοίου</para>
        /// </summary>
        [DescriptionAttribute("Στοιχεία Πλοίου")]
        [RequiredAttribute()]
        [XmlElementAttribute("shipId")]
        public string shipId { get; set; }
    }
}
