//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("TaxTotalsType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class TaxTotalsType
    {
        
        /// <summary>
        /// <para>Είδος Φόρου</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 5.</para>
        /// </summary>
        [DescriptionAttribute("Είδος Φόρου")]
        [RangeAttribute(typeof(sbyte), "1", "5")]
        [RequiredAttribute()]
        [XmlElementAttribute("taxType")]
        public sbyte taxType { get; set; }
        
        /// <summary>
        /// <para>Κατηγορία Φόρου</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Κατηγορία Φόρου")]
        [XmlElementAttribute("taxCategory")]
        public int taxCategory { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die taxCategory-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the taxCategory property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool taxCategorySpecified { get; set; }
        
        /// <summary>
        /// <para>Υποκείμενη Αξία</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [DescriptionAttribute("Υποκείμενη Αξία")]
        [XmlElementAttribute("underlyingValue")]
        public decimal underlyingValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die underlyingValue-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the underlyingValue property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool underlyingValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Ποσό Φόρου</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [DescriptionAttribute("Ποσό Φόρου")]
        [RequiredAttribute()]
        [XmlElementAttribute("taxAmount")]
        public decimal taxAmount { get; set; }
        
        [XmlElementAttribute("id")]
        public sbyte id { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die id-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the id property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool idSpecified { get; set; }
    }
}
