//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("TaxTotalsType", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class TaxTotalsType
    {
        
        /// <summary>
        /// <para>Είδος Φόρου</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 5.</para>
        /// </summary>
        [RangeAttribute(typeof(sbyte), "1", "5")]
        [RequiredAttribute()]
        [XmlElementAttribute("taxType")]
        public sbyte taxType { get; set; }
        
        /// <summary>
        /// <para>Κατηγορία Φόρου</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [XmlElementAttribute("taxCategory")]
        public Nullable<int> taxCategory { get; set; }
        
        /// <summary>
        /// <para>Υποκείμενη Αξία</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [XmlElementAttribute("underlyingValue")]
        public Nullable<decimal> underlyingValue { get; set; }
        
        /// <summary>
        /// <para>Ποσό Φόρου</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("taxAmount")]
        public decimal taxAmount { get; set; }
        
        [XmlElementAttribute("id")]
        public Nullable<sbyte> id { get; set; }
    }
}
