//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("RequestedDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0", AnonymousType=true)]
    [XmlRootAttribute("RequestedDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class RequestedDoc
    {
        
        [XmlElementAttribute("continuationToken")]
        public ContinuationTokenType continuationToken { get; set; }
        
        [XmlElementAttribute("invoicesDoc")]
        public RequestedDocinvoicesDoc invoicesDoc { get; set; }
        
        [XmlElementAttribute("cancelledInvoicesDoc")]
        public RequestedDoccancelledInvoicesDoc cancelledInvoicesDoc { get; set; }
        
        [XmlElementAttribute("incomeClassificationsDoc")]
        public RequestedDocincomeClassificationsDoc incomeClassificationsDoc { get; set; }
        
        [XmlElementAttribute("expensesClassificationsDoc")]
        public RequestedDocexpensesClassificationsDoc expensesClassificationsDoc { get; set; }
        
        [XmlElementAttribute("paymentMethodsDoc")]
        public RequestedDocpaymentMethodsDoc paymentMethodsDoc { get; set; }
    }
}
