//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("RequestedDocinvoicesDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0", AnonymousType=true)]
    public partial class RequestedDocinvoicesDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<MyData.Xsd.AadeBookInvoiceType> _invoice;
        
        [XmlElementAttribute("invoice")]
        public List<MyData.Xsd.AadeBookInvoiceType> invoice
        {
            get
            {
                return _invoice;
            }
            set
            {
                _invoice = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die invoice-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the invoice collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool invoiceSpecified
        {
            get
            {
                return ((this.invoice != null) 
                            && (this.invoice.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RequestedDocinvoicesDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestedDocinvoicesDoc" /> class.</para>
        /// </summary>
        public RequestedDocinvoicesDoc()
        {
            this._invoice = new List<MyData.Xsd.AadeBookInvoiceType>();
        }
    }
}
