//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("RequestedDocincomeClassificationsDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0", AnonymousType=true)]
    public partial class RequestedDocincomeClassificationsDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<MyData.Xsd.InvoiceIncomeClassificationType> _incomeInvoiceClassification;
        
        [XmlElementAttribute("incomeInvoiceClassification")]
        public List<MyData.Xsd.InvoiceIncomeClassificationType> incomeInvoiceClassification
        {
            get
            {
                return _incomeInvoiceClassification;
            }
            set
            {
                _incomeInvoiceClassification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die incomeInvoiceClassification-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the incomeInvoiceClassification collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool incomeInvoiceClassificationSpecified
        {
            get
            {
                return ((this.incomeInvoiceClassification != null) 
                            && (this.incomeInvoiceClassification.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RequestedDocincomeClassificationsDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestedDocincomeClassificationsDoc" /> class.</para>
        /// </summary>
        public RequestedDocincomeClassificationsDoc()
        {
            this._incomeInvoiceClassification = new List<MyData.Xsd.InvoiceIncomeClassificationType>();
        }
    }
}
