//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("RequestedDocexpensesClassificationsDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0", AnonymousType=true)]
    public partial class RequestedDocexpensesClassificationsDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<MyData.Xsd.InvoiceExpensesClassificationType> _expensesInvoiceClassification;
        
        [XmlElementAttribute("expensesInvoiceClassification")]
        public List<MyData.Xsd.InvoiceExpensesClassificationType> expensesInvoiceClassification
        {
            get
            {
                return _expensesInvoiceClassification;
            }
            set
            {
                _expensesInvoiceClassification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die expensesInvoiceClassification-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the expensesInvoiceClassification collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool expensesInvoiceClassificationSpecified
        {
            get
            {
                return ((this.expensesInvoiceClassification != null) 
                            && (this.expensesInvoiceClassification.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RequestedDocexpensesClassificationsDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestedDocexpensesClassificationsDoc" /> class.</para>
        /// </summary>
        public RequestedDocexpensesClassificationsDoc()
        {
            this._expensesInvoiceClassification = new List<MyData.Xsd.InvoiceExpensesClassificationType>();
        }
    }
}
