//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("RequestedDoccancelledInvoicesDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0", AnonymousType=true)]
    public partial class RequestedDoccancelledInvoicesDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<CancelledInvoiceType> _cancelledInvoice;
        
        [XmlElementAttribute("cancelledInvoice")]
        public List<CancelledInvoiceType> cancelledInvoice
        {
            get
            {
                return _cancelledInvoice;
            }
            set
            {
                _cancelledInvoice = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die cancelledInvoice-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the cancelledInvoice collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool cancelledInvoiceSpecified
        {
            get
            {
                return ((this.cancelledInvoice != null) 
                            && (this.cancelledInvoice.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RequestedDoccancelledInvoicesDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestedDoccancelledInvoicesDoc" /> class.</para>
        /// </summary>
        public RequestedDoccancelledInvoicesDoc()
        {
            this._cancelledInvoice = new List<CancelledInvoiceType>();
        }
    }
}
