//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("RequestedDocpaymentMethodsDoc", Namespace="http://www.aade.gr/myDATA/invoice/v1.0", AnonymousType=true)]
    public partial class RequestedDocpaymentMethodsDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<MyData.Xsd.PaymentMethodType> _paymentMethods;
        
        [XmlElementAttribute("paymentMethods")]
        public List<MyData.Xsd.PaymentMethodType> paymentMethods
        {
            get
            {
                return _paymentMethods;
            }
            set
            {
                _paymentMethods = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die paymentMethods-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the paymentMethods collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool paymentMethodsSpecified
        {
            get
            {
                return ((this.paymentMethods != null) 
                            && (this.paymentMethods.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="RequestedDocpaymentMethodsDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestedDocpaymentMethodsDoc" /> class.</para>
        /// </summary>
        public RequestedDocpaymentMethodsDoc()
        {
            this._paymentMethods = new List<MyData.Xsd.PaymentMethodType>();
        }
    }
}
