// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.41979 MIT License (MIT) 
//    <NameSpace>MyData.Xsd</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>True</GenerateSeparateFiles><OutputFilePath>InvoicesDoc-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyData.Xsd {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0", IsNullable=false)]
    public enum InvoiceType {
        
        
        [System.Xml.Serialization.XmlEnumAttribute("1.1")]
        Item11,       
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
        [System.Xml.Serialization.XmlEnumAttribute("1.3")]
        Item13,
        [System.Xml.Serialization.XmlEnumAttribute("1.4")]
        Item14,
        [System.Xml.Serialization.XmlEnumAttribute("1.5")]
        Item15,
        [System.Xml.Serialization.XmlEnumAttribute("1.6")]
        Item16,
        
        
        [System.Xml.Serialization.XmlEnumAttribute("2.1")]
        Item21,
        [System.Xml.Serialization.XmlEnumAttribute("2.2")]
        Item22,
        [System.Xml.Serialization.XmlEnumAttribute("2.3")]
        Item23,
        [System.Xml.Serialization.XmlEnumAttribute("2.4")]
        Item24,


        [System.Xml.Serialization.XmlEnumAttribute("3.1")]
        Item31,
        [System.Xml.Serialization.XmlEnumAttribute("3.2")]
        Item32,


        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,


        [System.Xml.Serialization.XmlEnumAttribute("5.1")]
        Item51,
        [System.Xml.Serialization.XmlEnumAttribute("5.2")]
        Item52,


        [System.Xml.Serialization.XmlEnumAttribute("6.1")]
        Item61,
        [System.Xml.Serialization.XmlEnumAttribute("6.2")]
        Item62,


        [System.Xml.Serialization.XmlEnumAttribute("7.1")]
        Item71,


        [System.Xml.Serialization.XmlEnumAttribute("8.1")]
        Item81,
        [System.Xml.Serialization.XmlEnumAttribute("8.2")]
        Item82,
        [System.Xml.Serialization.XmlEnumAttribute("8.4")]
        Item84,
        [System.Xml.Serialization.XmlEnumAttribute("8.5")]
        Item85,
        [System.Xml.Serialization.XmlEnumAttribute("8.6")]
        Item86,        
        

        [System.Xml.Serialization.XmlEnumAttribute("9.3")]
        Item93,        
        

        [System.Xml.Serialization.XmlEnumAttribute("11.1")]
        Item111,
        [System.Xml.Serialization.XmlEnumAttribute("11.2")]
        Item112,
        [System.Xml.Serialization.XmlEnumAttribute("11.3")]
        Item113,
        [System.Xml.Serialization.XmlEnumAttribute("11.4")]
        Item114,
        [System.Xml.Serialization.XmlEnumAttribute("11.5")]
        Item115,
        
        
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item121,     


        [System.Xml.Serialization.XmlEnumAttribute("13.1")]
        Item131,
        [System.Xml.Serialization.XmlEnumAttribute("13.2")]
        Item132,
        [System.Xml.Serialization.XmlEnumAttribute("13.3")]
        Item133,
        [System.Xml.Serialization.XmlEnumAttribute("13.4")]
        Item134,
        [System.Xml.Serialization.XmlEnumAttribute("13.30")]
        Item1330,
        [System.Xml.Serialization.XmlEnumAttribute("13.31")]
        Item1331,
        
        
        [System.Xml.Serialization.XmlEnumAttribute("14.1")]
        Item141,
        [System.Xml.Serialization.XmlEnumAttribute("14.2")]
        Item142,
        [System.Xml.Serialization.XmlEnumAttribute("14.3")]
        Item143,
        [System.Xml.Serialization.XmlEnumAttribute("14.4")]
        Item144,
        [System.Xml.Serialization.XmlEnumAttribute("14.5")]
        Item145,
        [System.Xml.Serialization.XmlEnumAttribute("14.30")]
        Item1430,
        [System.Xml.Serialization.XmlEnumAttribute("14.31")]
        Item1431,
        
        
        [System.Xml.Serialization.XmlEnumAttribute("15.1")]
        Item151,
        
        
        [System.Xml.Serialization.XmlEnumAttribute("16.1")]
        Item161,
        
        
        [System.Xml.Serialization.XmlEnumAttribute("17.1")]
        Item171,
        [System.Xml.Serialization.XmlEnumAttribute("17.2")]
        Item172,
        [System.Xml.Serialization.XmlEnumAttribute("17.3")]
        Item173,
        [System.Xml.Serialization.XmlEnumAttribute("17.4")]
        Item174,
        [System.Xml.Serialization.XmlEnumAttribute("17.5")]
        Item175,
        [System.Xml.Serialization.XmlEnumAttribute("17.6")]
        Item176,
    }
}
