// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.41979 MIT License (MIT) 
//    <NameSpace>MyData.Xsd</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>True</GenerateSeparateFiles><OutputFilePath>InvoicesDoc-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyData.Xsd {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0", IsNullable=true)]
    public partial class InvoiceHeaderType {
        
        public string series;
        
        public string aa;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime issueDate;
        
        public InvoiceType invoiceType;
        
        public bool vatPaymentSuspension;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vatPaymentSuspensionSpecified;
        
        public CurrencyType currency;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencySpecified;
        
        public decimal exchangeRate;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exchangeRateSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute("correlatedInvoices")]
        public List<long> correlatedInvoices;
        
        public bool selfPricing;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool selfPricingSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dispatchDate;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dispatchDateSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime dispatchTime;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dispatchTimeSpecified;
        
        public string vehicleNumber;
        
        public int movePurpose;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool movePurposeSpecified;
        
        public bool fuelInvoice;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuelInvoiceSpecified;
        
        public int specialInvoiceCategory;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool specialInvoiceCategorySpecified;
        
        public int invoiceVariationType;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invoiceVariationTypeSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute("otherCorrelatedEntities")]
        public List<EntityType> otherCorrelatedEntities;
        
        public OtherDeliveryNoteHeaderType otherDeliveryNoteHeader;
        
        public bool isDeliveryNote;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDeliveryNoteSpecified;
        
        public string otherMovePurposeTitle;
        
        public bool thirdPartyCollection;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thirdPartyCollectionSpecified;
        
        public InvoiceHeaderType() {
            this.otherDeliveryNoteHeader = new OtherDeliveryNoteHeaderType();
            this.otherCorrelatedEntities = new List<EntityType>();
            this.correlatedInvoices = new List<long>();
        }
    }
}
