// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.5224 MIT License (MIT) 
//    <NameSpace>AxMyData.AADE</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>False</GenerateSeparateFiles><OutputFilePath>incomeClassification-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AxMyData.AADE {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=false)]
    public partial class IncomeClassificationsDoc {
        
        private List<InvoiceIncomeClassificationType> incomeInvoiceClassificationField;
        
        public IncomeClassificationsDoc() {
            this.incomeInvoiceClassificationField = new List<InvoiceIncomeClassificationType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("incomeInvoiceClassification")]
        public List<InvoiceIncomeClassificationType> incomeInvoiceClassification {
            get {
                return this.incomeInvoiceClassificationField;
            }
            set {
                this.incomeInvoiceClassificationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=true)]
    public partial class InvoiceIncomeClassificationType {
        
        private long invoiceMarkField;
        
        private long classificationMarkField;
        
        private bool classificationMarkFieldSpecified;
        
        private string entityVatNumberField;
        
        private List<object> itemsField;
        
        public InvoiceIncomeClassificationType() {
            this.itemsField = new List<object>();
        }
        
        public long invoiceMark {
            get {
                return this.invoiceMarkField;
            }
            set {
                this.invoiceMarkField = value;
            }
        }
        
        public long classificationMark {
            get {
                return this.classificationMarkField;
            }
            set {
                this.classificationMarkField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationMarkSpecified {
            get {
                return this.classificationMarkFieldSpecified;
            }
            set {
                this.classificationMarkFieldSpecified = value;
            }
        }
        
        public string entityVatNumber {
            get {
                return this.entityVatNumberField;
            }
            set {
                this.entityVatNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("invoicesIncomeClassificationDetails", typeof(InvoicesIncomeClassificationDetailType))]
        [System.Xml.Serialization.XmlElementAttribute("transactionMode", typeof(int))]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=true)]
    public partial class InvoicesIncomeClassificationDetailType {
        
        private int lineNumberField;
        
        private List<IncomeClassificationType> incomeClassificationDetailDataField;
        
        public InvoicesIncomeClassificationDetailType() {
            this.incomeClassificationDetailDataField = new List<IncomeClassificationType>();
        }
        
        public int lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("incomeClassificationDetailData")]
        public List<IncomeClassificationType> incomeClassificationDetailData {
            get {
                return this.incomeClassificationDetailDataField;
            }
            set {
                this.incomeClassificationDetailDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=true)]
    public partial class IncomeClassificationType {
        
        private IncomeClassificationValueType classificationTypeField;
        
        private bool classificationTypeFieldSpecified;
        
        private IncomeClassificationCategoryType classificationCategoryField;
        
        private decimal amountField;
        
        private sbyte idField;
        
        private bool idFieldSpecified;
        
        public IncomeClassificationValueType classificationType {
            get {
                return this.classificationTypeField;
            }
            set {
                this.classificationTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool classificationTypeSpecified {
            get {
                return this.classificationTypeFieldSpecified;
            }
            set {
                this.classificationTypeFieldSpecified = value;
            }
        }
        
        public IncomeClassificationCategoryType classificationCategory {
            get {
                return this.classificationCategoryField;
            }
            set {
                this.classificationCategoryField = value;
            }
        }
        
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        public sbyte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=false)]
    public enum IncomeClassificationValueType {
        
        /// <remarks/>
        E3_106,
        
        /// <remarks/>
        E3_205,
        
        /// <remarks/>
        E3_210,
        
        /// <remarks/>
        E3_305,
        
        /// <remarks/>
        E3_310,
        
        /// <remarks/>
        E3_318,
        
        /// <remarks/>
        E3_561_001,
        
        /// <remarks/>
        E3_561_002,
        
        /// <remarks/>
        E3_561_003,
        
        /// <remarks/>
        E3_561_004,
        
        /// <remarks/>
        E3_561_005,
        
        /// <remarks/>
        E3_561_006,
        
        /// <remarks/>
        E3_561_007,
        
        /// <remarks/>
        E3_562,
        
        /// <remarks/>
        E3_563,
        
        /// <remarks/>
        E3_564,
        
        /// <remarks/>
        E3_565,
        
        /// <remarks/>
        E3_566,
        
        /// <remarks/>
        E3_567,
        
        /// <remarks/>
        E3_568,
        
        /// <remarks/>
        E3_570,
        
        /// <remarks/>
        E3_595,
        
        /// <remarks/>
        E3_596,
        
        /// <remarks/>
        E3_597,
        
        /// <remarks/>
        E3_880_001,
        
        /// <remarks/>
        E3_880_002,
        
        /// <remarks/>
        E3_880_003,
        
        /// <remarks/>
        E3_880_004,
        
        /// <remarks/>
        E3_881_001,
        
        /// <remarks/>
        E3_881_002,
        
        /// <remarks/>
        E3_881_003,
        
        /// <remarks/>
        E3_881_004,
        
        /// <remarks/>
        E3_598_001,
        
        /// <remarks/>
        E3_598_003,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0", IsNullable=false)]
    public enum IncomeClassificationCategoryType {
        
        /// <remarks/>
        category1_1,
        
        /// <remarks/>
        category1_2,
        
        /// <remarks/>
        category1_3,
        
        /// <remarks/>
        category1_4,
        
        /// <remarks/>
        category1_5,
        
        /// <remarks/>
        category1_6,
        
        /// <remarks/>
        category1_7,
        
        /// <remarks/>
        category1_8,
        
        /// <remarks/>
        category1_9,
        
        /// <remarks/>
        category1_10,
        
        /// <remarks/>
        category1_95,
        
        /// <remarks/>
        category3,
    }
}
