// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.5224 MIT License (MIT) 
//    <NameSpace>AxMyData.AADE</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>False</GenerateSeparateFiles><OutputFilePath>paymentMethods-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AxMyData.AADE {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0", IsNullable=false)]
    public partial class PaymentMethodsDoc {
        
        private List<PaymentMethodType> paymentMethodsField;
        
        public PaymentMethodsDoc() {
            this.paymentMethodsField = new List<PaymentMethodType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("paymentMethods")]
        public List<PaymentMethodType> paymentMethods {
            get {
                return this.paymentMethodsField;
            }
            set {
                this.paymentMethodsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.aade.gr/myDATA/paymentMethod/v1.0", IsNullable=true)]
    public partial class PaymentMethodType {
        
        private long invoiceMarkField;
        
        private long paymentMethodMarkField;
        
        private bool paymentMethodMarkFieldSpecified;
        
        private string entityVatNumberField;
        
        private List<PaymentMethodDetailType> paymentMethodDetailsField;
        
        public PaymentMethodType() {
            this.paymentMethodDetailsField = new List<PaymentMethodDetailType>();
        }
        
        public long invoiceMark {
            get {
                return this.invoiceMarkField;
            }
            set {
                this.invoiceMarkField = value;
            }
        }
        
        public long paymentMethodMark {
            get {
                return this.paymentMethodMarkField;
            }
            set {
                this.paymentMethodMarkField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentMethodMarkSpecified {
            get {
                return this.paymentMethodMarkFieldSpecified;
            }
            set {
                this.paymentMethodMarkFieldSpecified = value;
            }
        }
        
        public string entityVatNumber {
            get {
                return this.entityVatNumberField;
            }
            set {
                this.entityVatNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("paymentMethodDetails")]
        public List<PaymentMethodDetailType> paymentMethodDetails {
            get {
                return this.paymentMethodDetailsField;
            }
            set {
                this.paymentMethodDetailsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class PaymentMethodDetailType {
        
        private int typeField;
        
        private decimal amountField;
        
        private string paymentMethodInfoField;
        
        private decimal tipAmountField;
        
        private bool tipAmountFieldSpecified;
        
        private string transactionIdField;
        
        private ProviderSignatureType providersSignatureField;
        
        private ECRTokenType eCRTokenField;
        
        public PaymentMethodDetailType() {
            this.eCRTokenField = new ECRTokenType();
            this.providersSignatureField = new ProviderSignatureType();
        }
        
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        public string paymentMethodInfo {
            get {
                return this.paymentMethodInfoField;
            }
            set {
                this.paymentMethodInfoField = value;
            }
        }
        
        public decimal tipAmount {
            get {
                return this.tipAmountField;
            }
            set {
                this.tipAmountField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipAmountSpecified {
            get {
                return this.tipAmountFieldSpecified;
            }
            set {
                this.tipAmountFieldSpecified = value;
            }
        }
        
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        public ProviderSignatureType ProvidersSignature {
            get {
                return this.providersSignatureField;
            }
            set {
                this.providersSignatureField = value;
            }
        }
        
        public ECRTokenType ECRToken {
            get {
                return this.eCRTokenField;
            }
            set {
                this.eCRTokenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ProviderSignatureType {
        
        private string signingAuthorField;
        
        private string signatureField;
        
        public string SigningAuthor {
            get {
                return this.signingAuthorField;
            }
            set {
                this.signingAuthorField = value;
            }
        }
        
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    public partial class ECRTokenType {
        
        private string signingAuthorField;
        
        private string sessionNumberField;
        
        public string SigningAuthor {
            get {
                return this.signingAuthorField;
            }
            set {
                this.signingAuthorField = value;
            }
        }
        
        public string SessionNumber {
            get {
                return this.sessionNumberField;
            }
            set {
                this.sessionNumberField = value;
            }
        }
    }
}
