// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.5224 MIT License (MIT) 
//    <NameSpace>AxMyData.AADE</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>False</GenerateSeparateFiles><OutputFilePath>RequestedProviderDoc-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AxMyData.AADE {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RequestedProviderDoc {
        
        private List<continuationTokenType> continuationTokenField;
        
        private List<InvoiceProviderType> invoiceProviderTypeField;
        
        public RequestedProviderDoc() {
            this.invoiceProviderTypeField = new List<InvoiceProviderType>();
            this.continuationTokenField = new List<continuationTokenType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("continuationToken")]
        public List<continuationTokenType> continuationToken {
            get {
                return this.continuationTokenField;
            }
            set {
                this.continuationTokenField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("InvoiceProviderType")]
        public List<InvoiceProviderType> InvoiceProviderType {
            get {
                return this.invoiceProviderTypeField;
            }
            set {
                this.invoiceProviderTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class continuationTokenType {
        
        private string nextPartitionKeyField;
        
        private string nextRowKeyField;
        
        public string nextPartitionKey {
            get {
                return this.nextPartitionKeyField;
            }
            set {
                this.nextPartitionKeyField = value;
            }
        }
        
        public string nextRowKey {
            get {
                return this.nextRowKeyField;
            }
            set {
                this.nextRowKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class InvoiceProviderType {
        
        private string issuerVATField;
        
        private long invoiceProviderMarkField;
        
        private string invoiceUidField;
        
        private string authenticationCodeField;
        
        public string issuerVAT {
            get {
                return this.issuerVATField;
            }
            set {
                this.issuerVATField = value;
            }
        }
        
        public long invoiceProviderMark {
            get {
                return this.invoiceProviderMarkField;
            }
            set {
                this.invoiceProviderMarkField = value;
            }
        }
        
        public string invoiceUid {
            get {
                return this.invoiceUidField;
            }
            set {
                this.invoiceUidField = value;
            }
        }
        
        public string authenticationCode {
            get {
                return this.authenticationCodeField;
            }
            set {
                this.authenticationCodeField = value;
            }
        }
    }
}
