// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.5224 MIT License (MIT) 
//    <NameSpace>AxMyData.AADE</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>False</GenerateSeparateFiles><OutputFilePath>response-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AxMyData.AADE {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ResponseDoc {
        
        private List<ResponseType> responseField;
        
        public ResponseDoc() {
            this.responseField = new List<ResponseType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("response")]
        public List<ResponseType> response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ResponseType {
        
        private int indexField;
        
        private bool indexFieldSpecified;
        
        private List<object> itemsField;
        
        private List<ItemsChoiceType> itemsElementNameField;
        
        private string statusCodeField;
        
        public ResponseType() {
            this.itemsElementNameField = new List<ItemsChoiceType>();
            this.itemsField = new List<object>();
        }
        
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indexSpecified {
            get {
                return this.indexFieldSpecified;
            }
            set {
                this.indexFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("authenticationCode", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("cancellationMark", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("classificationMark", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("errors", typeof(ResponseTypeErrors))]
        [System.Xml.Serialization.XmlElementAttribute("invoiceMark", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("invoiceUid", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("paymentMethodMark", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("qrUrl", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("receptionEmails", typeof(receptionEmailsType))]
        [System.Xml.Serialization.XmlElementAttribute("receptionProviders", typeof(receptionProvidersType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public List<ItemsChoiceType> ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseTypeErrors {
        
        private List<ErrorType> errorField;
        
        public ResponseTypeErrors() {
            this.errorField = new List<ErrorType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("error")]
        public List<ErrorType> error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ErrorType {
        
        private string messageField;
        
        private string codeField;
        
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class receptionEmailsType {
        
        private List<string> emailField;
        
        public receptionEmailsType() {
            this.emailField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public List<string> email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class ProviderInfoType {
        
        private List<string> vATNumberField;
        
        public ProviderInfoType() {
            this.vATNumberField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("VATNumber")]
        public List<string> VATNumber {
            get {
                return this.vATNumberField;
            }
            set {
                this.vATNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class receptionProvidersType {
        
        private List<ProviderInfoType> providerInfoField;
        
        public receptionProvidersType() {
            this.providerInfoField = new List<ProviderInfoType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ProviderInfo")]
        public List<ProviderInfoType> ProviderInfo {
            get {
                return this.providerInfoField;
            }
            set {
                this.providerInfoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        authenticationCode,
        
        /// <remarks/>
        cancellationMark,
        
        /// <remarks/>
        classificationMark,
        
        /// <remarks/>
        errors,
        
        /// <remarks/>
        invoiceMark,
        
        /// <remarks/>
        invoiceUid,
        
        /// <remarks/>
        paymentMethodMark,
        
        /// <remarks/>
        qrUrl,
        
        /// <remarks/>
        receptionEmails,
        
        /// <remarks/>
        receptionProviders,
    }
}
