// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Open Xsd2Code. Version 3.4.2.41979 MIT License (MIT) 
//    <NameSpace>MyDataXsd</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><GenerateSeparateFiles>True</GenerateSeparateFiles><OutputFilePath>InvoicesDoc-v1.0.8.designer.cs</OutputFilePath><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><EnableEncoding>False</EnableEncoding><Encoder>UTF8</Encoder><UseBaseClass>False</UseBaseClass><BaseClassName>EntityBase</BaseClassName><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataXsd {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.1+6249aec1f88eb051eadc7d928205edd1c2d96aad")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aade.gr/myDATA/invoice/v1.0", IsNullable=false)]
    public enum CountryType {
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AW,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        BJ,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        BW,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        CX,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        EH,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        GF,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GS,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        IQ,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JE,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        KH,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        KP,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LK,
        
        /// <remarks/>
        LR,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        ME,
        
        /// <remarks/>
        MF,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MM,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        OC,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        PH,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PY,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SJ,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TJ,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        UA,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        US,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VG,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        VN,
        
        /// <remarks/>
        VU,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        YE,
        
        /// <remarks/>
        YT,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        ZM,
        
        /// <remarks/>
        ZW,
    }
}
