//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("IncomeClassificationType", Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public partial class IncomeClassificationType
    {
        
        /// <summary>
        /// <para>Κωδικός Χαρακτηρισμού</para>
        /// </summary>
        [DescriptionAttribute("Κωδικός Χαρακτηρισμού")]
        [XmlElementAttribute("classificationType")]
        public IncomeClassificationValueType classificationType { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die classificationType-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the classificationType property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool classificationTypeSpecified { get; set; }
        
        /// <summary>
        /// <para>Κατηγορία Χαρακτηρισμού</para>
        /// </summary>
        [DescriptionAttribute("Κατηγορία Χαρακτηρισμού")]
        [RequiredAttribute()]
        [XmlElementAttribute("classificationCategory")]
        public IncomeClassificationCategoryType classificationCategory { get; set; }
        
        /// <summary>
        /// <para>Ποσό Χαρακτηρισμού</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Total number of digits: 15.</para>
        /// </summary>
        [DescriptionAttribute("Ποσό Χαρακτηρισμού")]
        [RequiredAttribute()]
        [XmlElementAttribute("amount")]
        public decimal amount { get; set; }
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Χαρακτηρισμού</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Χαρακτηρισμού")]
        [XmlElementAttribute("id")]
        public sbyte id { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die id-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the id property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool idSpecified { get; set; }
    }
}
