//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("IncomeClassificationCategoryType", Namespace="https://www.aade.gr/myDATA/incomeClassificaton/v1.0")]
    public enum IncomeClassificationCategoryType
    {
        
        category1_1,
        
        category1_2,
        
        category1_3,
        
        category1_4,
        
        category1_5,
        
        category1_6,
        
        category1_7,
        
        category1_8,
        
        category1_9,
        
        category1_10,
        
        category1_95,
        
        category3,
    }
}
