//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ErrorType", Namespace="")]
    public partial class ErrorType
    {
        
        /// <summary>
        /// <para>Μήνυμα Σφάλματος</para>
        /// </summary>
        [DescriptionAttribute("Μήνυμα Σφάλματος")]
        [RequiredAttribute()]
        [XmlElementAttribute("message")]
        public string message { get; set; }
        
        /// <summary>
        /// <para>Κωδικός Σφάλαματος</para>
        /// </summary>
        [DescriptionAttribute("Κωδικός Σφάλαματος")]
        [RequiredAttribute()]
        [XmlElementAttribute("code")]
        public string code { get; set; }
    }
}
