//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProviderInfoType", Namespace="")]
    public partial class ProviderInfoType
    {
        
        [XmlIgnoreAttribute()]
        private List<string> _vATNumber;
        
        /// <summary>
        /// <para>ΑΦΜ</para>
        /// </summary>
        [DescriptionAttribute("ΑΦΜ")]
        [XmlElementAttribute("VATNumber")]
        public List<string> VATNumber
        {
            get
            {
                return _vATNumber;
            }
            set
            {
                _vATNumber = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die VATNumber-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the VATNumber collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool VATNumberSpecified
        {
            get
            {
                return ((this.VATNumber != null) 
                            && (this.VATNumber.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ProviderInfoType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProviderInfoType" /> class.</para>
        /// </summary>
        public ProviderInfoType()
        {
            this._vATNumber = new List<string>();
        }
    }
}
