//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Comment describing your root element</para>
    /// </summary>
    [DescriptionAttribute("Comment describing your root element")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ResponseDoc", Namespace="", AnonymousType=true)]
    [XmlRootAttribute("ResponseDoc", Namespace="")]
    public partial class ResponseDoc
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("response")]
        public List<ResponseType> response { get; set; }
    }
}
