//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ResponseType", Namespace="")]
    public partial class ResponseType
    {
        
        /// <summary>
        /// <para>ΑΑ γραμμής οντότητας</para>
        /// </summary>
        [DescriptionAttribute("ΑΑ γραμμής οντότητας")]
        [XmlElementAttribute("index")]
        public int index { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die index-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the index property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool indexSpecified { get; set; }
        
        /// <summary>
        /// <para>Αναγνωριστικό οντότητας</para>
        /// </summary>
        [DescriptionAttribute("Αναγνωριστικό οντότητας")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("invoiceUid")]
        public string invoiceUid { get; set; }
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Καταχώρησης παραστατικού</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Καταχώρησης παραστατικού")]
        [XmlElementAttribute("invoiceMark")]
        public long invoiceMark { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die invoiceMark-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the invoiceMark property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool invoiceMarkSpecified { get; set; }
        
        /// <summary>
        /// <para>QR Code Url</para>
        /// </summary>
        [DescriptionAttribute("QR Code Url")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("qrUrl")]
        public string qrUrl { get; set; }
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Παραλαβής Χαρακτηρισμού</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Παραλαβής Χαρακτηρισμού")]
        [XmlElementAttribute("classificationMark")]
        public long classificationMark { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die classificationMark-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the classificationMark property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool classificationMarkSpecified { get; set; }
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Ακύρωσης</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Ακύρωσης")]
        [XmlElementAttribute("cancellationMark")]
        public long cancellationMark { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die cancellationMark-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the cancellationMark property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool cancellationMarkSpecified { get; set; }
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Παραλαβής Τρόπου Πληρωμής</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Παραλαβής Τρόπου Πληρωμής")]
        [XmlElementAttribute("paymentMethodMark")]
        public long paymentMethodMark { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die paymentMethodMark-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the paymentMethodMark property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool paymentMethodMarkSpecified { get; set; }
        
        /// <summary>
        /// <para>Συμβολοσειρά Αυθεντικοποίησης Παρόχου</para>
        /// </summary>
        [DescriptionAttribute("Συμβολοσειρά Αυθεντικοποίησης Παρόχου")]
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("authenticationCode")]
        public string authenticationCode { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<ProviderInfoType> _receptionProviders;
        
        /// <summary>
        /// <para>Πάροχοι Λήπτη</para>
        /// </summary>
        [DescriptionAttribute("Πάροχοι Λήπτη")]
        [XmlArrayAttribute("receptionProviders")]
        [XmlArrayItemAttribute("ProviderInfo")]
        public List<ProviderInfoType> receptionProviders
        {
            get
            {
                return _receptionProviders;
            }
            set
            {
                _receptionProviders = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die receptionProviders-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the receptionProviders collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool receptionProvidersSpecified
        {
            get
            {
                return ((this.receptionProviders != null) 
                            && (this.receptionProviders.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ResponseType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ResponseType" /> class.</para>
        /// </summary>
        public ResponseType()
        {
            this._receptionProviders = new List<ProviderInfoType>();
            this._receptionEmails = new List<string>();
            this._errors = new List<ErrorType>();
        }
        
        [XmlIgnoreAttribute()]
        private List<string> _receptionEmails;
        
        /// <summary>
        /// <para>Email Παραλαβής</para>
        /// </summary>
        [DescriptionAttribute("Email Παραλαβής")]
        [XmlArrayAttribute("receptionEmails")]
        [XmlArrayItemAttribute("email")]
        public List<string> receptionEmails
        {
            get
            {
                return _receptionEmails;
            }
            set
            {
                _receptionEmails = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die receptionEmails-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the receptionEmails collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool receptionEmailsSpecified
        {
            get
            {
                return ((this.receptionEmails != null) 
                            && (this.receptionEmails.Count != 0));
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<ErrorType> _errors;
        
        /// <summary>
        /// <para>Λίστα Σφαλμάτων</para>
        /// </summary>
        [DescriptionAttribute("Λίστα Σφαλμάτων")]
        [XmlArrayAttribute("errors")]
        [XmlArrayItemAttribute("error")]
        public List<ErrorType> errors
        {
            get
            {
                return _errors;
            }
            set
            {
                _errors = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die errors-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the errors collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool errorsSpecified
        {
            get
            {
                return ((this.errors != null) 
                            && (this.errors.Count != 0));
            }
        }
        
        /// <summary>
        /// <para>Κωδικός αποτελέσματος</para>
        /// </summary>
        [DescriptionAttribute("Κωδικός αποτελέσματος")]
        [RequiredAttribute()]
        [XmlElementAttribute("statusCode")]
        public string statusCode { get; set; }
    }
}
