//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>Χαρατηρισμοί Εξόδων Πρότυπων Παραστατικών ΑΑΔΕ</para>
    /// </summary>
    [DescriptionAttribute("Χαρατηρισμοί Εξόδων Πρότυπων Παραστατικών ΑΑΔΕ")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ExpensesClassificationsDoc", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0", AnonymousType=true)]
    [XmlRootAttribute("ExpensesClassificationsDoc", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class ExpensesClassificationsDoc
    {
        
        [XmlIgnoreAttribute()]
        private List<InvoiceExpensesClassificationType> _expensesInvoiceClassification;
        
        [RequiredAttribute()]
        [XmlElementAttribute("expensesInvoiceClassification")]
        public List<InvoiceExpensesClassificationType> expensesInvoiceClassification
        {
            get
            {
                return _expensesInvoiceClassification;
            }
            set
            {
                _expensesInvoiceClassification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ExpensesClassificationsDoc" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ExpensesClassificationsDoc" /> class.</para>
        /// </summary>
        public ExpensesClassificationsDoc()
        {
            this._expensesInvoiceClassification = new List<InvoiceExpensesClassificationType>();
        }
    }
}
