//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ExpensesClassificationType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class ExpensesClassificationType
    {
        
        /// <summary>
        /// <para>Κωδικός Χαρακτηρισμού</para>
        /// </summary>
        [DescriptionAttribute("Κωδικός Χαρακτηρισμού")]
        [XmlElementAttribute("classificationType")]
        public ExpensesClassificationTypeclassificationType classificationType { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die classificationType-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the classificationType property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool classificationTypeSpecified { get; set; }
        
        /// <summary>
        /// <para>Κατηγορία Χαρακτηρισμού</para>
        /// </summary>
        [DescriptionAttribute("Κατηγορία Χαρακτηρισμού")]
        [XmlElementAttribute("classificationCategory")]
        public ExpensesClassificationCategoryType classificationCategory { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die classificationCategory-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the classificationCategory property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool classificationCategorySpecified { get; set; }
        
        /// <summary>
        /// <para>Ποσό Χαρακτηρισμού</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [DescriptionAttribute("Ποσό Χαρακτηρισμού")]
        [RequiredAttribute()]
        [XmlElementAttribute("amount")]
        public decimal amount { get; set; }
        
        /// <summary>
        /// <para>Πόσο Φόρου</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// </summary>
        [DescriptionAttribute("Πόσο Φόρου")]
        [XmlElementAttribute("vatAmount")]
        public decimal vatAmount { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die vatAmount-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the vatAmount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool vatAmountSpecified { get; set; }
        
        /// <summary>
        /// <para>Κατηγορία ΦΠΑ</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 8.</para>
        /// </summary>
        [DescriptionAttribute("Κατηγορία ΦΠΑ")]
        [RangeAttribute(typeof(int), "1", "8")]
        [XmlElementAttribute("vatCategory")]
        public int vatCategory { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die vatCategory-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the vatCategory property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool vatCategorySpecified { get; set; }
        
        /// <summary>
        /// <para>Κατηγορία Εξαίρεσης ΦΠΑ</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 31.</para>
        /// </summary>
        [DescriptionAttribute("Κατηγορία Εξαίρεσης ΦΠΑ")]
        [RangeAttribute(typeof(int), "1", "31")]
        [XmlElementAttribute("vatExemptionCategory")]
        public int vatExemptionCategory { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die vatExemptionCategory-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the vatExemptionCategory property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool vatExemptionCategorySpecified { get; set; }
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Χαρακτηρισμού</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Χαρακτηρισμού")]
        [XmlElementAttribute("id")]
        public sbyte id { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die id-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the id property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool idSpecified { get; set; }
    }
}
