//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 1.0.0.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoicesExpensesClassificationDetailType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class InvoicesExpensesClassificationDetailType
    {
        
        /// <summary>
        /// <para>Γραμμή Παραστατικού</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("lineNumber")]
        public int lineNumber { get; set; }
        
        /// <summary>
        /// <para>Λίστα Χαρακτηρισμών Εσόδων</para>
        /// </summary>
        [RequiredAttribute()]
        [XmlElementAttribute("expensesClassificationDetailData")]
        public List<ExpensesClassificationType> expensesClassificationDetailData { get; set; }
    }
}
