//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoiceExpensesClassificationType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class InvoiceExpensesClassificationType
    {
        
        /// <summary>
        /// <para>Μοναδικός Αριθμός Καταχώρησης Παραστατικού</para>
        /// </summary>
        [DescriptionAttribute("Μοναδικός Αριθμός Καταχώρησης Παραστατικού")]
        [RequiredAttribute()]
        [XmlElementAttribute("invoiceMark")]
        public long invoiceMark { get; set; }
        
        /// <summary>
        /// <para>Αποδεικτικό Λήψης Χαρακτηρισμού Εξόδων. Συμπληρώνεται από την Υπηρεσία</para>
        /// </summary>
        [DescriptionAttribute("Αποδεικτικό Λήψης Χαρακτηρισμού Εξόδων. Συμπληρώνεται από την Υπηρεσία")]
        [XmlElementAttribute("classificationMark")]
        public Nullable<long> classificationMark { get; set; }
        
        /// <summary>
        /// <para>ΑΦΜ Οντότητας Αναφοράς</para>
        /// </summary>
        [DescriptionAttribute("ΑΦΜ Οντότητας Αναφοράς")]
        [XmlElementAttribute("entityVatNumber")]
        public string entityVatNumber { get; set; }
        
        /// <summary>
        /// <para>Αιτιολογία Συναλλαγής</para>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2.</para>
        /// </summary>
        [DescriptionAttribute("Αιτιολογία Συναλλαγής")]
        [RangeAttribute(typeof(int), "1", "2")]
        [XmlElementAttribute("transactionMode")]
        public Nullable<int> transactionMode { get; set; }
        
        [XmlElementAttribute("invoicesExpensesClassificationDetails")]
        public List<InvoicesExpensesClassificationDetailType> invoicesExpensesClassificationDetails { get; set; }
        
        /// <summary>
        /// <para>Μέθοδος Υποβολής Χαρακτηρισμού</para>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 1.</para>
        /// </summary>
        [DescriptionAttribute("Μέθοδος Υποβολής Χαρακτηρισμού")]
        [RangeAttribute(typeof(sbyte), "0", "1")]
        [XmlElementAttribute("classificationPostMode")]
        public Nullable<sbyte> classificationPostMode { get; set; }
    }
}
