//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1057.0
namespace MyData.Xsd
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1057.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("InvoicesExpensesClassificationDetailType", Namespace="https://www.aade.gr/myDATA/expensesClassificaton/v1.0")]
    public partial class InvoicesExpensesClassificationDetailType
    {
        
        /// <summary>
        /// <para>Γραμμή Παραστατικού</para>
        /// </summary>
        [DescriptionAttribute("Γραμμή Παραστατικού")]
        [RequiredAttribute()]
        [XmlElementAttribute("lineNumber")]
        public int lineNumber { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<ExpensesClassificationType> _expensesClassificationDetailData;
        
        /// <summary>
        /// <para>Λίστα Χαρακτηρισμών Εσόδων</para>
        /// </summary>
        [DescriptionAttribute("Λίστα Χαρακτηρισμών Εσόδων")]
        [RequiredAttribute()]
        [XmlElementAttribute("expensesClassificationDetailData")]
        public List<ExpensesClassificationType> expensesClassificationDetailData
        {
            get
            {
                return _expensesClassificationDetailData;
            }
            set
            {
                _expensesClassificationDetailData = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="InvoicesExpensesClassificationDetailType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="InvoicesExpensesClassificationDetailType" /> class.</para>
        /// </summary>
        public InvoicesExpensesClassificationDetailType()
        {
            this._expensesClassificationDetailData = new List<ExpensesClassificationType>();
        }
    }
}
